/*
// Farrago is a relational database management system.
// Copyright (C) 2003-2004 John V. Sichi.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 2.1
// of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package net.sf.farrago.jdbc;

import net.sf.farrago.fem.fennel.*;

import java.sql.*;

/**
 * FarragoJdbcSavepoint implements the JDBC Savepoint interface for Farrago.
 *
 * @author John V. Sichi
 * @version $Id$
 */
public class FarragoJdbcSavepoint implements Savepoint
{
    /**
     * Connection which created this Savepoint.
     */
    Connection connection;
    
    /**
     * ID generated by Connection (unique within Connection scope).
     */
    int id;

    /**
     * Name assigned by user, or null if unnamed.
     */
    String name;

    /**
     * Handle to underlying Fennel savepoint.
     */
    FemSvptHandle femSvptHandle;

    FarragoJdbcSavepoint(
        int id,String name,FemSvptHandle femSvptHandle,Connection connection)
    {
        this.id = id;
        this.name = name;
        this.femSvptHandle = femSvptHandle;
        this.connection = connection;
    }
    
    // implement Savepoint
    public int getSavepointId() throws SQLException
    {
        if (name != null) {
            throw new SQLException("Can't getSavepointId for named Savepoint");
        }
        return id;
    }

    // implement Savepoint
    public String getSavepointName() throws SQLException
    {
        if (name == null) {
            throw new SQLException(
                "Can't getSavepointName for unnamed Savepoint");
        }
        return name;
    }

    // implement Object
    public boolean equals(Object obj)
    {
        if (!(obj instanceof FarragoJdbcSavepoint)) {
            return false;
        }
        FarragoJdbcSavepoint other = (FarragoJdbcSavepoint) obj;
        return (id == other.id) && (connection == other.connection);
    }

    // implement Object
    public int hashCode()
    {
        return id;
    }
}

// End FarragoJdbcSavepoint.java
