-- $Id$
-- This scripts tests the selectivity and cardinality data generated by
-- evaluating histograms.

!set verbose true
!set headerinterval 0

-- Create a flat file reader
create schema stat;
set schema 'stat';

create server stat_server
foreign data wrapper sys_file_wrapper
options (
    directory 'unitsql/optimizer/data',
    file_extension 'csv',
    with_header 'yes', 
    log_directory 'testlog');

create foreign table stat_file(
    "kseq" int not null,
    "k2" int not null,
    "k10" int not null,
    "k25" int not null,
    "k50" int not null,
    "k100" int not null,
    "k200" int not null)
server stat_server
options (filename 'stat');

-- Copy data to a regular table
create table stat(
    "kseq" int primary key,
    "k2" int not null,
    "k10" int not null,
    "k25" int not null,
    "k50" int not null,
    "k100" int not null,
    "k200" int not null);

insert into stat select * from stat_file;

-- Analyze all columns
analyze table stat compute statistics for all columns;

select
    "kseq",
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'kseq', cast("kseq" as varchar(20))) as sel,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'kseq', cast("kseq" as varchar(20))) as card
from stat;

select
    "k2",
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k2', cast("k2" as varchar(20))) as sel,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k2', cast("k2" as varchar(20))) as card
from (select distinct "k2" from stat)
order by "k2";

select
    "k10",
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10', cast("k10" as varchar(20))) as sel,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10', cast("k10" as varchar(20))) as card
from (select distinct "k10" from stat)
order by "k10";

select
    "k50",
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k50', cast("k50" as varchar(20))) as sel,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k50', cast("k50" as varchar(20))) as card
from (select distinct "k50" from stat)
order by "k50";

select
    "k100",
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k100', cast("k100" as varchar(20))) as sel,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k100', cast("k100" as varchar(20))) as card
from (select distinct "k100" from stat)
order by "k100";

select
    "k200",
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k200', cast("k200" as varchar(20))) as sel,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k200', cast("k200" as varchar(20))) as card
from (select distinct "k200" from stat)
order by "k200";

-- Compute selectivity and cardinality for distinct k10 values where exprssion
-- is > k10 (ge) or >= k10 (gte)
select
    "k10",
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '[' || cast("k10" as varchar(20))) as sel_gte,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '[' || cast("k10" as varchar(20))) as card_gte,
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '(' || cast("k10" as varchar(20))) as sel_gt,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '(' || cast("k10" as varchar(20))) as card_gt
from (select distinct "k10" from stat)
order by "k10";

-- Compute selectivity and cardinality for distinct k10 values where exprssion
-- is < k10 (le) or <= k10 (lte)
select
    "k10",
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        cast("k10" as varchar(20)) || ']') as sel_lte,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        cast("k10" as varchar(20)) || ']') as card_lte,
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        cast("k10" as varchar(20)) || ')') as sel_lt,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        cast("k10" as varchar(20)) || ')') as card_lt
from (select distinct "k10" from stat)
order by "k10";

-- Compute selectivity and cardinality for ranges on k10.  "cc" means both
-- ends closed, "oo" both ends open.
select
    "k10",
    low,
    high,
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '[' || low || ',' || high || ']') as sel_cc,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '[' || low || ',' || high || ']') as card_cc,
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '(' || low || ',' || high || ')') as sel_oo,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '(' || low || ',' || high || ')') as card_oo
from (
    select distinct
        "k10",
        cast("k10" - 2 as varchar(20)) as low,
        cast("k10" + 2 as varchar(20)) as high
    from stat);

-- More ranges with mismatched ends.
select
    "k10",
    low,
    high,
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '[' || low || ',' || high || ')') as sel_co,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '[' || low || ',' || high || ')') as card_co,
    sys_boot.mgmt.stat_get_selectivity(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '(' || low || ',' || high || ']') as sel_oc,
    sys_boot.mgmt.stat_get_cardinality(
        'LOCALDB', 'STAT', 'STAT', 'k10',
        '(' || low || ',' || high || ']') as card_oc
from (
    select distinct
        "k10",
        cast("k10" - 2 as varchar(20)) as low,
        cast("k10" + 2 as varchar(20)) as high
    from stat);
