SELECT SCHEMA_NAME FROM SYS_ROOT.DBA_SCHEMAS WHERE SCHEMA_NAME = 'TEST1111';
CALL APPLIB.EXEC_SQL_IF_NO_ROWS (
 'SELECT * FROM SYS_ROOT.DBA_SCHEMAS WHERE SCHEMA_NAME = ''TEST1111''',
 'CREATE SCHEMA TEST1111'
);
SELECT SCHEMA_NAME FROM SYS_ROOT.DBA_SCHEMAS WHERE SCHEMA_NAME = 'TEST1111';
CALL APPLIB.EXEC_SQL_IF_NO_ROWS (
 'SELECT * FROM SYS_ROOT.DBA_SCHEMAS WHERE SCHEMA_NAME = ''TEST1111''',
 'CREATE SCHEMA TEST1112'
);
SELECT SCHEMA_NAME FROM SYS_ROOT.DBA_SCHEMAS WHERE SCHEMA_NAME = 'TEST1112';
!set force true 
CALL APPLIB.EXEC_SQL_IF_NO_ROWS (
 'SELECT * BAD SQL',
 'CREATE SCHEMA TEST1112'
);
SELECT SCHEMA_NAME FROM SYS_ROOT.DBA_SCHEMAS WHERE SCHEMA_NAME = 'TEST1112';
DROP SCHEMA TEST1111;
