/*
// $Id$
// Saffron preprocessor and data engine
// (C) Copyright 2002-2003 Disruptive Technologies, Inc.
// (C) Copyright 2003-2004 John V. Sichi
// You must accept the terms in LICENSE.html to use this software.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 2.1
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package net.sf.saffron.oj.stmt;

import java.sql.*;


/**
 * PreparedResult represents the result of a call to Statement.prepareSql.
 *
 * @author John V. Sichi
 * @version $Id$
 */
public interface PreparedResult
{
    //~ Methods ---------------------------------------------------------------

    /**
     * @return the code generated by preparation
     */
    String getCode();

    /**
     * @return true iff this result is for a DML statement, in which case the
     *         result set is one row with one column containing the number of
     *         rows affected.
     */
    boolean isDml();

    /**
     * Execute the prepared result.
     *
     * @return producer of rows resulting from execution
     */
    Object execute();
}


// End PreparedResult.java
