#!/bin/sh
# $Id$
# Compress files generated by the CruiseControl process.
# Call this script from a cron job, as follows:
#
## # 4 AM: find all build logs more than 13 days old and compress them
## 00 04 * * * $HOME/open/bootstrap/compress-logfiles.sh

# Set LOGDIR to a sensible default.
if [ ! "$WEBDIR" ]; then
   export WEBDIR=$HOME/web
fi

export LOGDIR=$WEBDIR/logs

if [ ! -d "$LOGDIR" ]; then
   echo "Variable LOGDIR is not set or is not valid directory."
   exit 1
fi

export ARTDIR=$WEBDIR/artifacts

if [ ! -d "$ARTDIR" ]; then
   echo "Variable ARTDIR is not set or is not valid directory."
   exit 1
fi

debug=false

# Find all files more than 30 days old and delete them
find $LOGDIR -maxdepth 2 -daystart -mtime +30 \
 -not -name currentbuildstatus.txt \
 -not -name latest.xml \
 -type f \
 -exec rm {} ";" 

# Find all files more than 13 days old and compress them.
find $LOGDIR -maxdepth 2 -daystart -mtime +13 \
 -not -name "*.bz2" \
 -not -name currentbuildstatus.txt \
 -not -name latest.xml \
 -type f \
 -exec bzip2 {} ";" 

# If the directories contain no .xml files (because the last build was more
# than 13 days ago), decompress the most recent .xml.bz2
for i in $(find $LOGDIR/* -type d -maxdepth 0); do
   if [ "$(echo $i/*.xml)" = "$i/latest.xml" \
         -a "$(echo $i/*.xml.bz2)" != "$i/*.xml.bz2" ]; then
      mostRecent="$(ls $i/*.xml.bz2 | tail -1)"
      if [ -f "$mostRecent" ]; then
         $debug && echo "There are no .xml files in $i; decompressing the most recent .xml.bz2, $mostRecent"
         bzip2 -d "$mostRecent"
      fi
   fi

   rm -f $i/latest.xml
   # redirect stderr if file doesn't exist.
   mostRecentXml="$(ls $i/*.xml 2>/dev/null | tail -1)" 
   if [ "$mostRecentXml" != "" ]; then
       ln -s $mostRecentXml $i/latest.xml
   fi

done

for i in $(find $ARTDIR/* -type d -maxdepth 0); do
   rm -f $i/latest
   mostRecentDir="$(ls -d $(find $i/* -type d -maxdepth 0) | tail -1)"
   ln -s $mostRecentDir $i/latest
done

# End

