#!/bin/sh
# $Id$
# A script to process config-aspen.xml.src into a valid config-aspen.xml
# This preprocessing step avoids a lot of redundancy when dealing with multiple
# targets that are practically the same.

at=ASPENTARGET
p4s=P4SUFFIX
hlt=HEADERLINETOKEN
hlttext="<!-- Generated by config-aspen-generate.sh on `date` -->"

rm -f config-aspen.xml
for p4 in dev stable; do
	for t in aspen-debug aspen-opto; do
		sed "s/${at}/$t/g" config-aspen.xml.src | sed "s/.*${hlt}.*/${hlttext}/g" | sed "s/${p4s}/$p4/g" >> config-aspen.xml
	done;
done;
