#!/bin/sh
# $Id$
# A script to process config-aspen.xml.src into a valid config-aspen.xml
# This preprocessing step avoids a lot of redundancy when dealing with multiple
# targets that are practically the same.

at=ASPENTARGET
dt=DELETETOKEN
dttext="<!-- Generated by config-aspen-generate.sh on `date` -->"

rm -f config-aspen.xml
for t in aspen aspen-opto; do
	sed "s/${at}/$t/g" config-aspen.xml.src | sed "s/.*${dt}.*/${dttext}/g" >> config-aspen.xml
done;
