// This code generated by ProxyGen -- do not edit

enum AggFunction {
    AGG_FUNC_COUNT,
    AGG_FUNC_MAX,
    AGG_FUNC_MIN,
    AGG_FUNC_SINGLE_VALUE,
    AGG_FUNC_SUM
};

static std::string AggFunction_names[] = {"AGG_FUNC_COUNT","AGG_FUNC_MAX","AGG_FUNC_MIN","AGG_FUNC_SINGLE_VALUE","AGG_FUNC_SUM",""};

enum BarrierReturnMode {
    BARRIER_RET_ALL_INPUTS,
    BARRIER_RET_ANY_INPUT,
    BARRIER_RET_FIRST_INPUT
};

static std::string BarrierReturnMode_names[] = {"BARRIER_RET_ALL_INPUTS","BARRIER_RET_ANY_INPUT","BARRIER_RET_FIRST_INPUT",""};

enum CompOperator {
    COMP_EQ,
    COMP_GE,
    COMP_GT,
    COMP_LE,
    COMP_LT,
    COMP_NE,
    COMP_NOOP
};

static std::string CompOperator_names[] = {"COMP_EQ","COMP_GE","COMP_GT","COMP_LE","COMP_LT","COMP_NE","COMP_NOOP",""};

enum Distinctness {
    DUP_ALLOW,
    DUP_DISCARD,
    DUP_FAIL
};

static std::string Distinctness_names[] = {"DUP_ALLOW","DUP_DISCARD","DUP_FAIL",""};

enum TableSamplingMode {
    SAMPLING_BERNOULLI,
    SAMPLING_OFF,
    SAMPLING_SYSTEM
};

static std::string TableSamplingMode_names[] = {"SAMPLING_BERNOULLI","SAMPLING_OFF","SAMPLING_SYSTEM",""};

