// This code generated by ProxyGen -- do not edit

enum AggFunction {
    AGG_FUNC_SUM,
    AGG_FUNC_COUNT,
    AGG_FUNC_MIN,
    AGG_FUNC_MAX
};

static std::string AggFunction_names[] = {"AGG_FUNC_SUM","AGG_FUNC_COUNT","AGG_FUNC_MIN","AGG_FUNC_MAX",""};

enum CompOperator {
    COMP_NOOP,
    COMP_EQ,
    COMP_NE,
    COMP_LT,
    COMP_LE,
    COMP_GT,
    COMP_GE
};

static std::string CompOperator_names[] = {"COMP_NOOP","COMP_EQ","COMP_NE","COMP_LT","COMP_LE","COMP_GT","COMP_GE",""};

enum Distinctness {
    DUP_ALLOW,
    DUP_DISCARD,
    DUP_FAIL
};

static std::string Distinctness_names[] = {"DUP_ALLOW","DUP_DISCARD","DUP_FAIL",""};

