
-- aggDistinct.sql
-- test aggregation of distinct columns

set schema 's';

-- plain single distincts

SELECT COUNT(DISTINCT sex)
FROM EMP
;

SELECT SUM(DISTINCT sal)
FROM emp
;

SELECT MIN(DISTINCT SEX)
FROM EMP
;

SELECT MAX(DISTINCT SAL)
FROM EMP
;

SELECT AVG(DISTINCT SAL)
FROM EMP
;

-- plain single distincts with group bys
SELECT COUNT(DISTINCT SEX), DEPTNO
FROM EMP
GROUP BY DEPTNO
--ORDER BY *
ORDER BY 1,2
;

SELECT SUM(DISTINCT SAL), LNAME
FROM EMP
GROUP BY DEPTNO, LNAME
--ORDER BY *
ORDER BY 1,2
;

-- plain multiple distincts
SELECT COUNT(DISTINCT sex), SUM(DISTINCT sal)
FROM emp
;

SELECT COUNT(DISTINCT SAL), COUNT(DISTINCT SEX)
FROM EMP
;

SELECT COUNT(DISTINCT SEX), SUM(DISTINCT SAL),
MIN(DISTINCT SEX), MAX(DISTINCT SAL)
FROM EMP
;

-- mixing distinct and non-distinct, changing orders around, etc.

SELECT COUNT(DISTINCT SEX), COUNT(SEX), SUM(DISTINCT SAL), SUM(SAL), DEPTNO
FROM EMP GROUP BY DEPTNO ORDER BY *
;

SELECT COUNT(DISTINCT SEX), COUNT(SEX), SUM(DISTINCT SAL),
SUM(SAL), DEPTNO, LNAME
FROM EMP GROUP BY DEPTNO, LNAME ORDER BY *
;

SELECT COUNT(DISTINCT SEX), COUNT(SEX), DEPTNO, MIN(DISTINCT SAL),
SUM(DISTINCT SAL), SUM(SAL), DEPTNO
FROM EMP GROUP BY DEPTNO ORDER BY *
;

-- joins, baby, joins

SELECT COUNT(DISTINCT SEX), DEPT.DEPTNO, SUM(DISTINCT SAL)
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DEPT.DEPTNO
ORDER BY *
;

-- Select in from list

SELECT COUNT(DISTINCT SEX), SUM(DISTINCT SAL), DEPTNO
FROM
	(SELECT DNAME, DEPT.DEPTNO AS DEPTNO, SEX, SAL, LNAME
	 FROM EMP, DEPT
	 WHERE EMP.DEPTNO = DEPT.DEPTNO)
GROUP BY
	DEPTNO, DNAME
ORDER BY
	*
;


SELECT
	COUNT(DISTINCT SEX),
	SUM(DISTINCT SAL),
	DEPTNO,
	MIN(SAL),
	MAX(DISTINCT SAL),
	DNAME,
	AVG(DISTINCT SAL),
	COUNT(SEX),
	MIN(SEX),
	MIN(DISTINCT SEX)
FROM
	(SELECT DNAME, DEPT.DEPTNO AS DEPTNO, SEX, SAL, LNAME
	 FROM EMP, DEPT
	 WHERE EMP.DEPTNO = DEPT.DEPTNO)
GROUP BY
	DEPTNO, DNAME
ORDER BY
	*
;

-- SAME THING, DIFFERENT COLUMN ORDERS

SELECT
	MIN(SAL),
	DEPTNO,
	COUNT(SEX),
	MAX(DISTINCT SAL),
	DNAME,
	AVG(DISTINCT SAL),
	MIN(DISTINCT SEX),
	COUNT(DISTINCT SEX),
	SUM(DISTINCT SAL),
	MIN(SEX)
FROM
	(SELECT DEPT.DEPTNO AS DEPTNO, DNAME, SEX, SAL, LNAME
	 FROM EMP, DEPT
	 WHERE EMP.DEPTNO = DEPT.DEPTNO)
GROUP BY
	DEPTNO, DNAME
ORDER BY
	*
;

-- EVEN WORSE...

SELECT
	MIN(SAL),
	DEPTNO,
	COUNT(SEX),
	MAX(DISTINCT SAL),
	DNAME,
	AVG(DISTINCT SAL),
	MIN(DISTINCT SEX),
	COUNT(DISTINCT SEX),
	SUM(DISTINCT SAL),
	MIN(SEX)
FROM
	(SELECT DEPT.DEPTNO AS DEPTNO, DNAME, SEX, SAL, LNAME
	 FROM EMP, DEPT
	 WHERE EMP.DEPTNO = DEPT.DEPTNO)
GROUP BY
	DEPTNO, DNAME
ORDER BY
	(SELECT COUNT(DISTINCT SEX) FROM EMP), DEPTNO
;

-- AGg in group by
SELECT COUNT(DISTINCT DEPTNO) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO
;

SELECT COUNT(DISTINCT SEX) FROM EMP GROUP BY DEPTNO, SEX ORDER BY DEPTNO
;

SELECT COUNT(DISTINCT SEX), DEPTNO FROM EMP
GROUP BY DEPTNO, SEX ORDER BY *
;

SELECT
	DEPTNO, DNAME, COUNT(DISTINCT SEX), MIN(DISTINCT DNAME)
FROM
	(SELECT DEPT.DEPTNO AS DEPTNO, DNAME, SEX, SAL, LNAME
	 FROM EMP, DEPT
	 WHERE EMP.DEPTNO = DEPT.DEPTNO)
GROUP BY
	DEPTNO, DNAME
ORDER BY
	*
;


-- FRINGE CASES

SELECT COUNT(DISTINCT 1) FROM EMP GROUP BY DEPTNO ORDER BY *
;

SELECT COUNT(DISTINCT SEX) * 5 + 15 FROM EMP
;

-- USER DEFINED

SELECT COUNT(DISTINCT SEX) FROM EMP GROUP BY DEPTNO ORDER BY *
;

SELECT SUM(DISTINCT SAL), COUNT(DISTINCT SEX) FROM EMP
;
