
--
-- range joins
--

set schema 's';

-- workarounds put in for LER-92 and LER-93
-- a big ol' join
select SALES.CUSTID, SALES.PRODID, SALES.PRICE, PRODUCTS.PRICE
from SALES, PRODUCTS
where SALES.PRICE between PRODUCTS.PRICE - 1 and PRODUCTS.PRICE + 1
and SALES.PRODID = PRODUCTS.PRODID
order by  CUSTID, PRODID, PRICE;

-- non join conditions
select PRODUCTS.NAME, SALES.CUSTID
from SALES, PRODUCTS
where SALES.PRICE between PRODUCTS.PRICE - 1 and PRODUCTS.PRICE + 1
and ( PRODUCTS.NAME LIKE 'C%' OR PRODUCTS.NAME LIKE 'P%')
order by NAME, CUSTID;

-- equality and non equality in one
select SALES.CUSTID, PRODUCTS.NAME, CUSTOMERS.FNAME, CUSTOMERS.LNAME,
PRODUCTS.PRICE, SALES.PRICE, PRODUCTS.PRICE-SALES.PRICE
from SALES, PRODUCTS, CUSTOMERS
where SALES.PRICE - PRODUCTS.PRICE < 0.5
and PRODUCTS.PRICE - SALES.PRICE < 0.25
and SALES.CUSTID = CUSTOMERS.CUSTID
order by NAME, CUSTID, PRICE, PRICE;

-- TODO: date ranges
-- select S1.CUSTID, S1.EMPNO, S1.TS, S2.CUSTID, S2.EMPNO, S2.TS,
-- from SALES S1, SALES S2
-- where S1.TS between S2.TS -1 and S2.TS +1
-- order by S1.CUSTID, S1.EMPNO, S1.TS, S2.CUSTID, S2.EMPNO, S2.TS;

