
--
-- Equi-joins
--

set schema 's';

-- workarounds put in for LER-92 and LER-93
-- standard emp/dept
select EMP.EMPNO, EMP.LNAME, EMP.DEPTNO, DEPT.DEPTNO, DEPT.DNAME
from EMP, DEPT
where EMP.DEPTNO = DEPT.DEPTNO order by EMPNO;

-- this one used to fail in calculator due to column mapping stuff
select EMP.EMPNO, EMP.DEPTNO, DEPT.DNAME from EMP, DEPT
where EMP.DEPTNO = DEPT.DEPTNO order by EMPNO;

-- dept, loc
select DEPTNO, DNAME, CITY, LOCATION.LOCID from DEPT, LOCATION
where DEPT.LOCID=LOCATION.LOCID
order by DEPTNO, LOCID;

-- three way join, table A -> B -> C
SELECT EMP.LNAME, DEPT.DNAME, LOCATION.CITY
from EMP, DEPT, LOCATION
where EMP.DEPTNO=DEPT.DEPTNO and DEPT.LOCID=LOCATION.LOCID
order by LNAME;

-- three way shuffled a bit
select CUSTOMERS.CUSTID, CUSTOMERS.FNAME, CUSTOMERS.LNAME, PRODUCTS.NAME, SALES.PRICE
from CUSTOMERS, SALES, PRODUCTS
where CUSTOMERS.CUSTID=SALES.CUSTID and PRODUCTS.PRODID = SALES.PRODID
order by CUSTID, NAME, PRICE;

select CUSTOMERS.CUSTID, EMP.LNAME, CUSTOMERS.LNAME, PRODUCTS.NAME, SALES.PRICE
from CUSTOMERS, SALES, PRODUCTS, EMP
where CUSTOMERS.CUSTID=SALES.CUSTID and PRODUCTS.PRODID = SALES.PRODID
and EMP.EMPNO = SALES.EMPNO
order by CUSTID, PRICE, NAME;

-- self join of emp
select M.LNAME, R.LNAME, R.EMPNO from EMP M, EMP R
where M.EMPNO = R.MANAGER order by EMPNO;

-- double reference of a table
select EL.CITY, DL.CITY, EMP.LNAME, DEPT.DNAME
from LOCATION EL, LOCATION DL, EMP, DEPT
where EL.LOCID = EMP.LOCID and DL.LOCID=DEPT.LOCID
order by LNAME, CITY, CITY, DNAME;

-- many to many query
select PRODUCTS.NAME, PRODUCTS.PRICE, SALES.PRICE
from SALES, PRODUCTS where SALES.PRICE=PRODUCTS.PRICE
order by NAME, PRICE, PRICE;

-- many to many self join
select M.FNAME ,F.FNAME, M.LNAME
FROM CUSTOMERS M, CUSTOMERS F
WHERE M.LNAME = F.LNAME
AND M.SEX = 'M'
AND F.SEX = 'F'
order by FNAME, FNAME, LNAME;
