#!/bin/bash
# $Id$
# Run the sqlline command-line SQL interpreter 
# with an embedded Firewater engine

SESSION_FACTORY="./plugin/firewater.jar"

SERVER_JAVA_ARGS="-Xms512m -Xmx512m -ea -esa \
  -cp ./plugin/firewater-jdbc.jar:`cat ../farrago/classpath.gen`:../farrago/plugin/FarragoMedJdbc.jar \
  -Dnet.sf.farrago.home=`pwd` \
  -Dnet.sf.farrago.catalog=`pwd`/catalog/data \
  -Djava.util.logging.config.file=./trace/FirewaterTrace.properties \
  -Dnet.sf.farrago.defaultSessionFactoryLibraryName=${SESSION_FACTORY}"

SQLLINE_JAVA_ARGS="sqlline.SqlLine"

if java ${SERVER_JAVA_ARGS} ${SQLLINE_JAVA_ARGS} \
    -u jdbc:firewater: -d net.sf.firewater.jdbc.FirewaterLocalDriver \
    -n sa $*;
then
    echo
else
    tset
    echo "Terminal reset because sqlline crashed"
fi
