// This code generated by ProxyGen -- do not edit

class ProxyBufferingTupleStreamDef;
typedef JniProxyIter<ProxyBufferingTupleStreamDef> SharedProxyBufferingTupleStreamDef;

class ProxyCalcTupleStreamDef;
typedef JniProxyIter<ProxyCalcTupleStreamDef> SharedProxyCalcTupleStreamDef;

class ProxyCartesianProductStreamDef;
typedef JniProxyIter<ProxyCartesianProductStreamDef> SharedProxyCartesianProductStreamDef;

class ProxyCmd;
typedef JniProxyIter<ProxyCmd> SharedProxyCmd;

class ProxyCmdBeginTxn;
typedef JniProxyIter<ProxyCmdBeginTxn> SharedProxyCmdBeginTxn;

class ProxyCmdCheckpoint;
typedef JniProxyIter<ProxyCmdCheckpoint> SharedProxyCmdCheckpoint;

class ProxyCmdCloseDatabase;
typedef JniProxyIter<ProxyCmdCloseDatabase> SharedProxyCmdCloseDatabase;

class ProxyCmdCommit;
typedef JniProxyIter<ProxyCmdCommit> SharedProxyCmdCommit;

class ProxyCmdCreateExecutionStreamGraph;
typedef JniProxyIter<ProxyCmdCreateExecutionStreamGraph> SharedProxyCmdCreateExecutionStreamGraph;

class ProxyCmdCreateIndex;
typedef JniProxyIter<ProxyCmdCreateIndex> SharedProxyCmdCreateIndex;

class ProxyCmdCreateStreamHandle;
typedef JniProxyIter<ProxyCmdCreateStreamHandle> SharedProxyCmdCreateStreamHandle;

class ProxyCmdDropIndex;
typedef JniProxyIter<ProxyCmdDropIndex> SharedProxyCmdDropIndex;

class ProxyCmdOpenDatabase;
typedef JniProxyIter<ProxyCmdOpenDatabase> SharedProxyCmdOpenDatabase;

class ProxyCmdPrepareExecutionStreamGraph;
typedef JniProxyIter<ProxyCmdPrepareExecutionStreamGraph> SharedProxyCmdPrepareExecutionStreamGraph;

class ProxyCmdRollback;
typedef JniProxyIter<ProxyCmdRollback> SharedProxyCmdRollback;

class ProxyCmdSavepoint;
typedef JniProxyIter<ProxyCmdSavepoint> SharedProxyCmdSavepoint;

class ProxyCmdTruncateIndex;
typedef JniProxyIter<ProxyCmdTruncateIndex> SharedProxyCmdTruncateIndex;

class ProxyDatabaseCmd;
typedef JniProxyIter<ProxyDatabaseCmd> SharedProxyDatabaseCmd;

class ProxyDatabaseParam;
typedef JniProxyIter<ProxyDatabaseParam> SharedProxyDatabaseParam;

class ProxyDbHandle;
typedef JniProxyIter<ProxyDbHandle> SharedProxyDbHandle;

class ProxyEndTxnCmd;
typedef JniProxyIter<ProxyEndTxnCmd> SharedProxyEndTxnCmd;

class ProxyExecutionStreamDef;
typedef JniProxyIter<ProxyExecutionStreamDef> SharedProxyExecutionStreamDef;

class ProxyHandle;
typedef JniProxyIter<ProxyHandle> SharedProxyHandle;

class ProxyIndexAccessorDef;
typedef JniProxyIter<ProxyIndexAccessorDef> SharedProxyIndexAccessorDef;

class ProxyIndexCmd;
typedef JniProxyIter<ProxyIndexCmd> SharedProxyIndexCmd;

class ProxyIndexLoaderDef;
typedef JniProxyIter<ProxyIndexLoaderDef> SharedProxyIndexLoaderDef;

class ProxyIndexScanDef;
typedef JniProxyIter<ProxyIndexScanDef> SharedProxyIndexScanDef;

class ProxyIndexSearchDef;
typedef JniProxyIter<ProxyIndexSearchDef> SharedProxyIndexSearchDef;

class ProxyIndexStreamDef;
typedef JniProxyIter<ProxyIndexStreamDef> SharedProxyIndexStreamDef;

class ProxyIndexWriterDef;
typedef JniProxyIter<ProxyIndexWriterDef> SharedProxyIndexWriterDef;

class ProxyJavaTupleStreamDef;
typedef JniProxyIter<ProxyJavaTupleStreamDef> SharedProxyJavaTupleStreamDef;

class ProxyKeyAccessorDef;
typedef JniProxyIter<ProxyKeyAccessorDef> SharedProxyKeyAccessorDef;

class ProxySortingStreamDef;
typedef JniProxyIter<ProxySortingStreamDef> SharedProxySortingStreamDef;

class ProxyStreamGraphHandle;
typedef JniProxyIter<ProxyStreamGraphHandle> SharedProxyStreamGraphHandle;

class ProxyStreamHandle;
typedef JniProxyIter<ProxyStreamHandle> SharedProxyStreamHandle;

class ProxySvptHandle;
typedef JniProxyIter<ProxySvptHandle> SharedProxySvptHandle;

class ProxyTableDeleterDef;
typedef JniProxyIter<ProxyTableDeleterDef> SharedProxyTableDeleterDef;

class ProxyTableInserterDef;
typedef JniProxyIter<ProxyTableInserterDef> SharedProxyTableInserterDef;

class ProxyTableUpdaterDef;
typedef JniProxyIter<ProxyTableUpdaterDef> SharedProxyTableUpdaterDef;

class ProxyTableWriterDef;
typedef JniProxyIter<ProxyTableWriterDef> SharedProxyTableWriterDef;

class ProxyTupleAccessor;
typedef JniProxyIter<ProxyTupleAccessor> SharedProxyTupleAccessor;

class ProxyTupleAttrAccessor;
typedef JniProxyIter<ProxyTupleAttrAccessor> SharedProxyTupleAttrAccessor;

class ProxyTupleAttrDescriptor;
typedef JniProxyIter<ProxyTupleAttrDescriptor> SharedProxyTupleAttrDescriptor;

class ProxyTupleAttrProjection;
typedef JniProxyIter<ProxyTupleAttrProjection> SharedProxyTupleAttrProjection;

class ProxyTupleDescriptor;
typedef JniProxyIter<ProxyTupleDescriptor> SharedProxyTupleDescriptor;

class ProxyTupleProjection;
typedef JniProxyIter<ProxyTupleProjection> SharedProxyTupleProjection;

class ProxyTupleStreamDef;
typedef JniProxyIter<ProxyTupleStreamDef> SharedProxyTupleStreamDef;

class ProxyTupleStreamGraphCmd;
typedef JniProxyIter<ProxyTupleStreamGraphCmd> SharedProxyTupleStreamGraphCmd;

class ProxyTxnCmd;
typedef JniProxyIter<ProxyTxnCmd> SharedProxyTxnCmd;

class ProxyTxnHandle;
typedef JniProxyIter<ProxyTxnHandle> SharedProxyTxnHandle;

class ProxyExecutionStreamDef
: virtual public JniProxy
{
public:
std::string getName();
static jmethodID meth_getName;
SharedProxyExecutionStreamDef getInput();
static jmethodID meth_getInput;
SharedProxyTupleDescriptor getOutputDesc();
static jmethodID meth_getOutputDesc;
SharedProxyExecutionStreamDef getConsumer();
static jmethodID meth_getConsumer;
};

class ProxyTupleStreamDef
: virtual public JniProxy, virtual public ProxyExecutionStreamDef
{
public:
};

class ProxyBufferingTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
bool isInMemory();
static jmethodID meth_isInMemory;
bool isMultipass();
static jmethodID meth_isMultipass;
};

class ProxyCalcTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
std::string getProgram();
static jmethodID meth_getProgram;
bool isFilter();
static jmethodID meth_isFilter;
};

class ProxyCartesianProductStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
};

class ProxyCmd
: virtual public JniProxy
{
public:
};

class ProxyDatabaseCmd
: virtual public JniProxy, virtual public ProxyCmd
{
public:
SharedProxyDbHandle getDbHandle();
static jmethodID meth_getDbHandle;
};

class ProxyCmdBeginTxn
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
SharedProxyTxnHandle getResultHandle();
static jmethodID meth_getResultHandle;
};

class ProxyCmdCheckpoint
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
bool isFuzzy();
static jmethodID meth_isFuzzy;
bool isAsync();
static jmethodID meth_isAsync;
};

class ProxyCmdCloseDatabase
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
};

class ProxyTxnCmd
: virtual public JniProxy, virtual public ProxyCmd
{
public:
SharedProxyTxnHandle getTxnHandle();
static jmethodID meth_getTxnHandle;
};

class ProxyEndTxnCmd
: virtual public JniProxy, virtual public ProxyTxnCmd
{
public:
SharedProxySvptHandle getSvptHandle();
static jmethodID meth_getSvptHandle;
};

class ProxyCmdCommit
: virtual public JniProxy, virtual public ProxyEndTxnCmd
{
public:
};

class ProxyCmdCreateExecutionStreamGraph
: virtual public JniProxy, virtual public ProxyTxnCmd
{
public:
SharedProxyStreamGraphHandle getResultHandle();
static jmethodID meth_getResultHandle;
};

class ProxyIndexCmd
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
int64_t getSegmentId();
static jmethodID meth_getSegmentId;
int64_t getIndexId();
static jmethodID meth_getIndexId;
SharedProxyTupleDescriptor getTupleDesc();
static jmethodID meth_getTupleDesc;
SharedProxyTupleProjection getKeyProj();
static jmethodID meth_getKeyProj;
};

class ProxyCmdCreateIndex
: virtual public JniProxy, virtual public ProxyIndexCmd
{
public:
};

class ProxyTupleStreamGraphCmd
: virtual public JniProxy, virtual public ProxyCmd
{
public:
SharedProxyStreamGraphHandle getStreamGraphHandle();
static jmethodID meth_getStreamGraphHandle;
};

class ProxyCmdCreateStreamHandle
: virtual public JniProxy, virtual public ProxyTupleStreamGraphCmd
{
public:
SharedProxyStreamHandle getResultHandle();
static jmethodID meth_getResultHandle;
std::string getStreamName();
static jmethodID meth_getStreamName;
};

class ProxyCmdDropIndex
: virtual public JniProxy, virtual public ProxyIndexCmd
{
public:
int64_t getRootPageId();
static jmethodID meth_getRootPageId;
};

class ProxyCmdOpenDatabase
: virtual public JniProxy, virtual public ProxyCmd
{
public:
SharedProxyDbHandle getResultHandle();
static jmethodID meth_getResultHandle;
bool isCreateDatabase();
static jmethodID meth_isCreateDatabase;
int64_t getJavaTraceHandle();
static jmethodID meth_getJavaTraceHandle;
SharedProxyDatabaseParam getParams();
static jmethodID meth_getParams;
};

class ProxyCmdPrepareExecutionStreamGraph
: virtual public JniProxy, virtual public ProxyTupleStreamGraphCmd
{
public:
SharedProxyExecutionStreamDef getStreamDefs();
static jmethodID meth_getStreamDefs;
};

class ProxyCmdRollback
: virtual public JniProxy, virtual public ProxyEndTxnCmd
{
public:
};

class ProxyCmdSavepoint
: virtual public JniProxy, virtual public ProxyTxnCmd
{
public:
SharedProxySvptHandle getResultHandle();
static jmethodID meth_getResultHandle;
};

class ProxyCmdTruncateIndex
: virtual public JniProxy, virtual public ProxyCmdDropIndex
{
public:
};

class ProxyDatabaseParam
: virtual public JniProxy
{
public:
std::string getName();
static jmethodID meth_getName;
std::string getValue();
static jmethodID meth_getValue;
};

class ProxyHandle
: virtual public JniProxy
{
public:
int64_t getLongHandle();
static jmethodID meth_getLongHandle;
};

class ProxyDbHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class ProxyKeyAccessorDef
: virtual public JniProxy
{
public:
SharedProxyTupleProjection getKeyProj();
static jmethodID meth_getKeyProj;
};

class ProxyIndexAccessorDef
: virtual public JniProxy, virtual public ProxyKeyAccessorDef
{
public:
int64_t getRootPageId();
static jmethodID meth_getRootPageId;
int64_t getSegmentId();
static jmethodID meth_getSegmentId;
int64_t getIndexId();
static jmethodID meth_getIndexId;
SharedProxyTupleDescriptor getTupleDesc();
static jmethodID meth_getTupleDesc;
};

class ProxyIndexStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef, virtual public ProxyIndexAccessorDef
{
public:
};

class ProxyIndexLoaderDef
: virtual public JniProxy, virtual public ProxyIndexStreamDef
{
public:
Distinctness getDistinctness();
static jmethodID meth_getDistinctness;
};

class ProxyIndexScanDef
: virtual public JniProxy, virtual public ProxyIndexStreamDef
{
public:
SharedProxyTupleProjection getOutputProj();
static jmethodID meth_getOutputProj;
};

class ProxyIndexSearchDef
: virtual public JniProxy, virtual public ProxyIndexScanDef
{
public:
bool isUniqueKey();
static jmethodID meth_isUniqueKey;
bool isOuterJoin();
static jmethodID meth_isOuterJoin;
SharedProxyTupleProjection getInputKeyProj();
static jmethodID meth_getInputKeyProj;
SharedProxyTupleProjection getInputJoinProj();
static jmethodID meth_getInputJoinProj;
};

class ProxyIndexWriterDef
: virtual public JniProxy, virtual public ProxyIndexAccessorDef
{
public:
SharedProxyTupleProjection getInputProj();
static jmethodID meth_getInputProj;
Distinctness getDistinctness();
static jmethodID meth_getDistinctness;
bool isUpdateInPlace();
static jmethodID meth_isUpdateInPlace;
};

class ProxyJavaTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
int32_t getStreamId();
static jmethodID meth_getStreamId;
};

class ProxySortingStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef, virtual public ProxyKeyAccessorDef
{
public:
Distinctness getDistinctness();
static jmethodID meth_getDistinctness;
};

class ProxyStreamGraphHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class ProxyStreamHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class ProxySvptHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class ProxyTableWriterDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
SharedProxyIndexWriterDef getIndexWriter();
static jmethodID meth_getIndexWriter;
};

class ProxyTableDeleterDef
: virtual public JniProxy, virtual public ProxyTableWriterDef
{
public:
};

class ProxyTableInserterDef
: virtual public JniProxy, virtual public ProxyTableWriterDef
{
public:
};

class ProxyTableUpdaterDef
: virtual public JniProxy, virtual public ProxyTableWriterDef
{
public:
SharedProxyTupleProjection getUpdateProj();
static jmethodID meth_getUpdateProj;
};

class ProxyTupleAccessor
: virtual public JniProxy
{
public:
int32_t getMinByteLength();
static jmethodID meth_getMinByteLength;
int32_t getBitFieldOffset();
static jmethodID meth_getBitFieldOffset;
SharedProxyTupleAttrAccessor getAttrAccessor();
static jmethodID meth_getAttrAccessor;
};

class ProxyTupleAttrAccessor
: virtual public JniProxy
{
public:
int32_t getNullBitIndex();
static jmethodID meth_getNullBitIndex;
int32_t getFixedOffset();
static jmethodID meth_getFixedOffset;
int32_t getEndIndirectOffset();
static jmethodID meth_getEndIndirectOffset;
int32_t getBitValueIndex();
static jmethodID meth_getBitValueIndex;
};

class ProxyTupleAttrDescriptor
: virtual public JniProxy
{
public:
int32_t getTypeOrdinal();
static jmethodID meth_getTypeOrdinal;
bool isNullable();
static jmethodID meth_isNullable;
int32_t getByteLength();
static jmethodID meth_getByteLength;
};

class ProxyTupleAttrProjection
: virtual public JniProxy
{
public:
int32_t getAttributeIndex();
static jmethodID meth_getAttributeIndex;
};

class ProxyTupleDescriptor
: virtual public JniProxy
{
public:
SharedProxyTupleAttrDescriptor getAttrDescriptor();
static jmethodID meth_getAttrDescriptor;
};

class ProxyTupleProjection
: virtual public JniProxy
{
public:
SharedProxyTupleAttrProjection getAttrProjection();
static jmethodID meth_getAttrProjection;
};

class ProxyTxnHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class FemVisitor : virtual public JniProxyVisitor
{
public:
static JniProxyVisitTable<FemVisitor> visitTbl;
virtual void visit(ProxyBufferingTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyCalcTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyCartesianProductStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdBeginTxn &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCheckpoint &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCloseDatabase &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCommit &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCreateExecutionStreamGraph &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCreateIndex &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCreateStreamHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdDropIndex &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdOpenDatabase &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdPrepareExecutionStreamGraph &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdRollback &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdSavepoint &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdTruncateIndex &)
{ unhandledVisit(); }
virtual void visit(ProxyDatabaseCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyDatabaseParam &)
{ unhandledVisit(); }
virtual void visit(ProxyDbHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyEndTxnCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyExecutionStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexAccessorDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexLoaderDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexScanDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexSearchDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexWriterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyJavaTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyKeyAccessorDef &)
{ unhandledVisit(); }
virtual void visit(ProxySortingStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyStreamGraphHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyStreamHandle &)
{ unhandledVisit(); }
virtual void visit(ProxySvptHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyTableDeleterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTableInserterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTableUpdaterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTableWriterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleAccessor &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleAttrAccessor &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleAttrDescriptor &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleAttrProjection &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleDescriptor &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleProjection &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleStreamGraphCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyTxnCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyTxnHandle &)
{ unhandledVisit(); }
};

