// This code generated by ProxyGen -- do not edit

class ProxyAggInvocation;
typedef JniProxyIter<ProxyAggInvocation> SharedProxyAggInvocation;

class ProxyAggStreamDef;
typedef JniProxyIter<ProxyAggStreamDef> SharedProxyAggStreamDef;

class ProxyBarrierStreamDef;
typedef JniProxyIter<ProxyBarrierStreamDef> SharedProxyBarrierStreamDef;

class ProxyBeginTxnCmd;
typedef JniProxyIter<ProxyBeginTxnCmd> SharedProxyBeginTxnCmd;

class ProxyBernoulliSamplingStreamDef;
typedef JniProxyIter<ProxyBernoulliSamplingStreamDef> SharedProxyBernoulliSamplingStreamDef;

class ProxyBufferReaderStreamDef;
typedef JniProxyIter<ProxyBufferReaderStreamDef> SharedProxyBufferReaderStreamDef;

class ProxyBufferWriterStreamDef;
typedef JniProxyIter<ProxyBufferWriterStreamDef> SharedProxyBufferWriterStreamDef;

class ProxyBufferingTupleStreamDef;
typedef JniProxyIter<ProxyBufferingTupleStreamDef> SharedProxyBufferingTupleStreamDef;

class ProxyCalcTupleStreamDef;
typedef JniProxyIter<ProxyCalcTupleStreamDef> SharedProxyCalcTupleStreamDef;

class ProxyCartesianProductStreamDef;
typedef JniProxyIter<ProxyCartesianProductStreamDef> SharedProxyCartesianProductStreamDef;

class ProxyCmd;
typedef JniProxyIter<ProxyCmd> SharedProxyCmd;

class ProxyCmdAbandonBackup;
typedef JniProxyIter<ProxyCmdAbandonBackup> SharedProxyCmdAbandonBackup;

class ProxyCmdAlterSystemDeallocate;
typedef JniProxyIter<ProxyCmdAlterSystemDeallocate> SharedProxyCmdAlterSystemDeallocate;

class ProxyCmdBeginTxn;
typedef JniProxyIter<ProxyCmdBeginTxn> SharedProxyCmdBeginTxn;

class ProxyCmdBeginTxnWithCsn;
typedef JniProxyIter<ProxyCmdBeginTxnWithCsn> SharedProxyCmdBeginTxnWithCsn;

class ProxyCmdCheckpoint;
typedef JniProxyIter<ProxyCmdCheckpoint> SharedProxyCmdCheckpoint;

class ProxyCmdCloseDatabase;
typedef JniProxyIter<ProxyCmdCloseDatabase> SharedProxyCmdCloseDatabase;

class ProxyCmdCommit;
typedef JniProxyIter<ProxyCmdCommit> SharedProxyCmdCommit;

class ProxyCmdCompleteBackup;
typedef JniProxyIter<ProxyCmdCompleteBackup> SharedProxyCmdCompleteBackup;

class ProxyCmdCreateExecutionStreamGraph;
typedef JniProxyIter<ProxyCmdCreateExecutionStreamGraph> SharedProxyCmdCreateExecutionStreamGraph;

class ProxyCmdCreateIndex;
typedef JniProxyIter<ProxyCmdCreateIndex> SharedProxyCmdCreateIndex;

class ProxyCmdCreateStreamHandle;
typedef JniProxyIter<ProxyCmdCreateStreamHandle> SharedProxyCmdCreateStreamHandle;

class ProxyCmdDropIndex;
typedef JniProxyIter<ProxyCmdDropIndex> SharedProxyCmdDropIndex;

class ProxyCmdGetLastCommittedTxnId;
typedef JniProxyIter<ProxyCmdGetLastCommittedTxnId> SharedProxyCmdGetLastCommittedTxnId;

class ProxyCmdGetTxnCsn;
typedef JniProxyIter<ProxyCmdGetTxnCsn> SharedProxyCmdGetTxnCsn;

class ProxyCmdInitiateBackup;
typedef JniProxyIter<ProxyCmdInitiateBackup> SharedProxyCmdInitiateBackup;

class ProxyCmdOpenDatabase;
typedef JniProxyIter<ProxyCmdOpenDatabase> SharedProxyCmdOpenDatabase;

class ProxyCmdPrepareExecutionStreamGraph;
typedef JniProxyIter<ProxyCmdPrepareExecutionStreamGraph> SharedProxyCmdPrepareExecutionStreamGraph;

class ProxyCmdRestoreFromBackup;
typedef JniProxyIter<ProxyCmdRestoreFromBackup> SharedProxyCmdRestoreFromBackup;

class ProxyCmdRollback;
typedef JniProxyIter<ProxyCmdRollback> SharedProxyCmdRollback;

class ProxyCmdSavepoint;
typedef JniProxyIter<ProxyCmdSavepoint> SharedProxyCmdSavepoint;

class ProxyCmdSetParam;
typedef JniProxyIter<ProxyCmdSetParam> SharedProxyCmdSetParam;

class ProxyCmdTruncateIndex;
typedef JniProxyIter<ProxyCmdTruncateIndex> SharedProxyCmdTruncateIndex;

class ProxyCmdVerifyIndex;
typedef JniProxyIter<ProxyCmdVerifyIndex> SharedProxyCmdVerifyIndex;

class ProxyCmdVersionIndexRoot;
typedef JniProxyIter<ProxyCmdVersionIndexRoot> SharedProxyCmdVersionIndexRoot;

class ProxyCollectTupleStreamDef;
typedef JniProxyIter<ProxyCollectTupleStreamDef> SharedProxyCollectTupleStreamDef;

class ProxyColumnName;
typedef JniProxyIter<ProxyColumnName> SharedProxyColumnName;

class ProxyCorrelation;
typedef JniProxyIter<ProxyCorrelation> SharedProxyCorrelation;

class ProxyCorrelationJoinStreamDef;
typedef JniProxyIter<ProxyCorrelationJoinStreamDef> SharedProxyCorrelationJoinStreamDef;

class ProxyCsnHandle;
typedef JniProxyIter<ProxyCsnHandle> SharedProxyCsnHandle;

class ProxyCsnHandleReturningCmd;
typedef JniProxyIter<ProxyCsnHandleReturningCmd> SharedProxyCsnHandleReturningCmd;

class ProxyDatabaseCmd;
typedef JniProxyIter<ProxyDatabaseCmd> SharedProxyDatabaseCmd;

class ProxyDatabaseParam;
typedef JniProxyIter<ProxyDatabaseParam> SharedProxyDatabaseParam;

class ProxyDbHandle;
typedef JniProxyIter<ProxyDbHandle> SharedProxyDbHandle;

class ProxyDynamicParamUse;
typedef JniProxyIter<ProxyDynamicParamUse> SharedProxyDynamicParamUse;

class ProxyDynamicParameter;
typedef JniProxyIter<ProxyDynamicParameter> SharedProxyDynamicParameter;

class ProxyEndTxnCmd;
typedef JniProxyIter<ProxyEndTxnCmd> SharedProxyEndTxnCmd;

class ProxyExecStreamDataFlow;
typedef JniProxyIter<ProxyExecStreamDataFlow> SharedProxyExecStreamDataFlow;

class ProxyExecutionStreamDef;
typedef JniProxyIter<ProxyExecutionStreamDef> SharedProxyExecutionStreamDef;

class ProxyFlatFileTupleStreamDef;
typedef JniProxyIter<ProxyFlatFileTupleStreamDef> SharedProxyFlatFileTupleStreamDef;

class ProxyGenericStreamDef;
typedef JniProxyIter<ProxyGenericStreamDef> SharedProxyGenericStreamDef;

class ProxyHandle;
typedef JniProxyIter<ProxyHandle> SharedProxyHandle;

class ProxyIndexAccessCmd;
typedef JniProxyIter<ProxyIndexAccessCmd> SharedProxyIndexAccessCmd;

class ProxyIndexAccessorDef;
typedef JniProxyIter<ProxyIndexAccessorDef> SharedProxyIndexAccessorDef;

class ProxyIndexCmd;
typedef JniProxyIter<ProxyIndexCmd> SharedProxyIndexCmd;

class ProxyIndexLoaderDef;
typedef JniProxyIter<ProxyIndexLoaderDef> SharedProxyIndexLoaderDef;

class ProxyIndexScanDef;
typedef JniProxyIter<ProxyIndexScanDef> SharedProxyIndexScanDef;

class ProxyIndexSearchDef;
typedef JniProxyIter<ProxyIndexSearchDef> SharedProxyIndexSearchDef;

class ProxyIndexStreamDef;
typedef JniProxyIter<ProxyIndexStreamDef> SharedProxyIndexStreamDef;

class ProxyIndexWriterDef;
typedef JniProxyIter<ProxyIndexWriterDef> SharedProxyIndexWriterDef;

class ProxyJavaSinkStreamDef;
typedef JniProxyIter<ProxyJavaSinkStreamDef> SharedProxyJavaSinkStreamDef;

class ProxyJavaTransformStreamDef;
typedef JniProxyIter<ProxyJavaTransformStreamDef> SharedProxyJavaTransformStreamDef;

class ProxyKeyAccessorDef;
typedef JniProxyIter<ProxyKeyAccessorDef> SharedProxyKeyAccessorDef;

class ProxyLbmBitOpStreamDef;
typedef JniProxyIter<ProxyLbmBitOpStreamDef> SharedProxyLbmBitOpStreamDef;

class ProxyLbmChopperStreamDef;
typedef JniProxyIter<ProxyLbmChopperStreamDef> SharedProxyLbmChopperStreamDef;

class ProxyLbmGeneratorStreamDef;
typedef JniProxyIter<ProxyLbmGeneratorStreamDef> SharedProxyLbmGeneratorStreamDef;

class ProxyLbmIntersectStreamDef;
typedef JniProxyIter<ProxyLbmIntersectStreamDef> SharedProxyLbmIntersectStreamDef;

class ProxyLbmMinusStreamDef;
typedef JniProxyIter<ProxyLbmMinusStreamDef> SharedProxyLbmMinusStreamDef;

class ProxyLbmNormalizerStreamDef;
typedef JniProxyIter<ProxyLbmNormalizerStreamDef> SharedProxyLbmNormalizerStreamDef;

class ProxyLbmSearchStreamDef;
typedef JniProxyIter<ProxyLbmSearchStreamDef> SharedProxyLbmSearchStreamDef;

class ProxyLbmSortedAggStreamDef;
typedef JniProxyIter<ProxyLbmSortedAggStreamDef> SharedProxyLbmSortedAggStreamDef;

class ProxyLbmSplicerStreamDef;
typedef JniProxyIter<ProxyLbmSplicerStreamDef> SharedProxyLbmSplicerStreamDef;

class ProxyLbmUnionStreamDef;
typedef JniProxyIter<ProxyLbmUnionStreamDef> SharedProxyLbmUnionStreamDef;

class ProxyLcsClusterAppendStreamDef;
typedef JniProxyIter<ProxyLcsClusterAppendStreamDef> SharedProxyLcsClusterAppendStreamDef;

class ProxyLcsClusterReplaceStreamDef;
typedef JniProxyIter<ProxyLcsClusterReplaceStreamDef> SharedProxyLcsClusterReplaceStreamDef;

class ProxyLcsClusterScanDef;
typedef JniProxyIter<ProxyLcsClusterScanDef> SharedProxyLcsClusterScanDef;

class ProxyLcsRowScanStreamDef;
typedef JniProxyIter<ProxyLcsRowScanStreamDef> SharedProxyLcsRowScanStreamDef;

class ProxyLhxAggStreamDef;
typedef JniProxyIter<ProxyLhxAggStreamDef> SharedProxyLhxAggStreamDef;

class ProxyLhxJoinStreamDef;
typedef JniProxyIter<ProxyLhxJoinStreamDef> SharedProxyLhxJoinStreamDef;

class ProxyMergeStreamDef;
typedef JniProxyIter<ProxyMergeStreamDef> SharedProxyMergeStreamDef;

class ProxyMockTupleStreamDef;
typedef JniProxyIter<ProxyMockTupleStreamDef> SharedProxyMockTupleStreamDef;

class ProxyMultiUseBufferingStreamDef;
typedef JniProxyIter<ProxyMultiUseBufferingStreamDef> SharedProxyMultiUseBufferingStreamDef;

class ProxyNestedLoopJoinStreamDef;
typedef JniProxyIter<ProxyNestedLoopJoinStreamDef> SharedProxyNestedLoopJoinStreamDef;

class ProxyReshapeParameter;
typedef JniProxyIter<ProxyReshapeParameter> SharedProxyReshapeParameter;

class ProxyReshapeStreamDef;
typedef JniProxyIter<ProxyReshapeStreamDef> SharedProxyReshapeStreamDef;

class ProxySortedAggStreamDef;
typedef JniProxyIter<ProxySortedAggStreamDef> SharedProxySortedAggStreamDef;

class ProxySortingStreamDef;
typedef JniProxyIter<ProxySortingStreamDef> SharedProxySortingStreamDef;

class ProxySplicerIndexAccessorDef;
typedef JniProxyIter<ProxySplicerIndexAccessorDef> SharedProxySplicerIndexAccessorDef;

class ProxySplitterStreamDef;
typedef JniProxyIter<ProxySplitterStreamDef> SharedProxySplitterStreamDef;

class ProxyStreamGraphHandle;
typedef JniProxyIter<ProxyStreamGraphHandle> SharedProxyStreamGraphHandle;

class ProxyStreamHandle;
typedef JniProxyIter<ProxyStreamHandle> SharedProxyStreamHandle;

class ProxySvptHandle;
typedef JniProxyIter<ProxySvptHandle> SharedProxySvptHandle;

class ProxyTableDeleterDef;
typedef JniProxyIter<ProxyTableDeleterDef> SharedProxyTableDeleterDef;

class ProxyTableInserterDef;
typedef JniProxyIter<ProxyTableInserterDef> SharedProxyTableInserterDef;

class ProxyTableUpdaterDef;
typedef JniProxyIter<ProxyTableUpdaterDef> SharedProxyTableUpdaterDef;

class ProxyTableWriterDef;
typedef JniProxyIter<ProxyTableWriterDef> SharedProxyTableWriterDef;

class ProxyTupleAccessor;
typedef JniProxyIter<ProxyTupleAccessor> SharedProxyTupleAccessor;

class ProxyTupleAttrAccessor;
typedef JniProxyIter<ProxyTupleAttrAccessor> SharedProxyTupleAttrAccessor;

class ProxyTupleAttrDescriptor;
typedef JniProxyIter<ProxyTupleAttrDescriptor> SharedProxyTupleAttrDescriptor;

class ProxyTupleAttrProjection;
typedef JniProxyIter<ProxyTupleAttrProjection> SharedProxyTupleAttrProjection;

class ProxyTupleDescriptor;
typedef JniProxyIter<ProxyTupleDescriptor> SharedProxyTupleDescriptor;

class ProxyTupleProjection;
typedef JniProxyIter<ProxyTupleProjection> SharedProxyTupleProjection;

class ProxyTupleStreamDef;
typedef JniProxyIter<ProxyTupleStreamDef> SharedProxyTupleStreamDef;

class ProxyTupleStreamGraphCmd;
typedef JniProxyIter<ProxyTupleStreamGraphCmd> SharedProxyTupleStreamGraphCmd;

class ProxyTxnCmd;
typedef JniProxyIter<ProxyTxnCmd> SharedProxyTxnCmd;

class ProxyTxnHandle;
typedef JniProxyIter<ProxyTxnHandle> SharedProxyTxnHandle;

class ProxyUncollectTupleStreamDef;
typedef JniProxyIter<ProxyUncollectTupleStreamDef> SharedProxyUncollectTupleStreamDef;

class ProxyValuesStreamDef;
typedef JniProxyIter<ProxyValuesStreamDef> SharedProxyValuesStreamDef;

class ProxyWindowDef;
typedef JniProxyIter<ProxyWindowDef> SharedProxyWindowDef;

class ProxyWindowPartitionDef;
typedef JniProxyIter<ProxyWindowPartitionDef> SharedProxyWindowPartitionDef;

class ProxyWindowStreamDef;
typedef JniProxyIter<ProxyWindowStreamDef> SharedProxyWindowStreamDef;

class FENNEL_FARRAGO_EXPORT ProxyAggInvocation
: virtual public JniProxy
{
public:
SharedProxyAggStreamDef getAggStreamDef();
static jmethodID meth_getAggStreamDef;
AggFunction getFunction();
static jmethodID meth_getFunction;
int32_t getInputAttributeIndex();
static jmethodID meth_getInputAttributeIndex;
};

class FENNEL_FARRAGO_EXPORT ProxyExecutionStreamDef
: virtual public JniProxy
{
public:
SharedProxyDynamicParamUse getDynamicParamUse();
static jmethodID meth_getDynamicParamUse;
SharedProxyExecStreamDataFlow getInputFlow();
static jmethodID meth_getInputFlow;
std::string getName();
static jmethodID meth_getName;
SharedProxyTupleDescriptor getOutputDesc();
static jmethodID meth_getOutputDesc;
SharedProxyExecStreamDataFlow getOutputFlow();
static jmethodID meth_getOutputFlow;
};

class FENNEL_FARRAGO_EXPORT ProxyTupleStreamDef
: virtual public JniProxy, virtual public ProxyExecutionStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyAggStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
SharedProxyAggInvocation getAggInvocation();
static jmethodID meth_getAggInvocation;
int32_t getGroupingPrefixSize();
static jmethodID meth_getGroupingPrefixSize;
};

class FENNEL_FARRAGO_EXPORT ProxyBarrierStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
SharedProxyDynamicParameter getDynamicParameter();
static jmethodID meth_getDynamicParameter;
BarrierReturnMode getReturnMode();
static jmethodID meth_getReturnMode;
};

class FENNEL_FARRAGO_EXPORT ProxyCmd
: virtual public JniProxy
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyDatabaseCmd
: virtual public JniProxy, virtual public ProxyCmd
{
public:
SharedProxyDbHandle getDbHandle();
static jmethodID meth_getDbHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyBeginTxnCmd
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
SharedProxyTxnHandle getResultHandle();
static jmethodID meth_getResultHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyBernoulliSamplingStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
int32_t getRepeatableSeed();
static jmethodID meth_getRepeatableSeed;
bool isRepeatable();
static jmethodID meth_isRepeatable;
float getSamplingRate();
static jmethodID meth_getSamplingRate;
};

class FENNEL_FARRAGO_EXPORT ProxyBufferingTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
bool isInMemory();
static jmethodID meth_isInMemory;
bool isMultipass();
static jmethodID meth_isMultipass;
};

class FENNEL_FARRAGO_EXPORT ProxyMultiUseBufferingStreamDef
: virtual public JniProxy, virtual public ProxyBufferingTupleStreamDef
{
public:
int32_t getReaderRefCountParamId();
static jmethodID meth_getReaderRefCountParamId;
};

class FENNEL_FARRAGO_EXPORT ProxyBufferReaderStreamDef
: virtual public JniProxy, virtual public ProxyMultiUseBufferingStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyBufferWriterStreamDef
: virtual public JniProxy, virtual public ProxyMultiUseBufferingStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyCalcTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
bool isFilter();
static jmethodID meth_isFilter;
std::string getProgram();
static jmethodID meth_getProgram;
};

class FENNEL_FARRAGO_EXPORT ProxyCartesianProductStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
bool isLeftOuter();
static jmethodID meth_isLeftOuter;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdAbandonBackup
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyCmdAlterSystemDeallocate
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
int64_t getOldestLabelCsn();
static jmethodID meth_getOldestLabelCsn;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdBeginTxn
: virtual public JniProxy, virtual public ProxyBeginTxnCmd
{
public:
bool isReadOnly();
static jmethodID meth_isReadOnly;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdBeginTxnWithCsn
: virtual public JniProxy, virtual public ProxyBeginTxnCmd
{
public:
SharedProxyCsnHandle getCsnHandle();
static jmethodID meth_getCsnHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdCheckpoint
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
bool isAsync();
static jmethodID meth_isAsync;
bool isFuzzy();
static jmethodID meth_isFuzzy;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdCloseDatabase
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyTxnCmd
: virtual public JniProxy, virtual public ProxyCmd
{
public:
SharedProxyTxnHandle getTxnHandle();
static jmethodID meth_getTxnHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyEndTxnCmd
: virtual public JniProxy, virtual public ProxyTxnCmd
{
public:
SharedProxySvptHandle getSvptHandle();
static jmethodID meth_getSvptHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdCommit
: virtual public JniProxy, virtual public ProxyEndTxnCmd
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyCmdCompleteBackup
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
int64_t getLowerBoundCsn();
static jmethodID meth_getLowerBoundCsn;
int64_t getUpperBoundCsn();
static jmethodID meth_getUpperBoundCsn;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdCreateExecutionStreamGraph
: virtual public JniProxy, virtual public ProxyTxnCmd
{
public:
SharedProxyStreamGraphHandle getResultHandle();
static jmethodID meth_getResultHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyIndexCmd
: virtual public JniProxy, virtual public ProxyTxnCmd
{
public:
int64_t getIndexId();
static jmethodID meth_getIndexId;
SharedProxyTupleProjection getKeyProj();
static jmethodID meth_getKeyProj;
SharedProxyTupleProjection getLeafPageIdProj();
static jmethodID meth_getLeafPageIdProj;
int64_t getSegmentId();
static jmethodID meth_getSegmentId;
SharedProxyTupleDescriptor getTupleDesc();
static jmethodID meth_getTupleDesc;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdCreateIndex
: virtual public JniProxy, virtual public ProxyIndexCmd
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyTupleStreamGraphCmd
: virtual public JniProxy, virtual public ProxyCmd
{
public:
SharedProxyStreamGraphHandle getStreamGraphHandle();
static jmethodID meth_getStreamGraphHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdCreateStreamHandle
: virtual public JniProxy, virtual public ProxyTupleStreamGraphCmd
{
public:
bool isInput();
static jmethodID meth_isInput;
SharedProxyStreamHandle getResultHandle();
static jmethodID meth_getResultHandle;
std::string getStreamName();
static jmethodID meth_getStreamName;
};

class FENNEL_FARRAGO_EXPORT ProxyIndexAccessCmd
: virtual public JniProxy, virtual public ProxyIndexCmd
{
public:
int64_t getRootPageId();
static jmethodID meth_getRootPageId;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdDropIndex
: virtual public JniProxy, virtual public ProxyIndexAccessCmd
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyCsnHandleReturningCmd
: virtual public JniProxy
{
public:
SharedProxyCsnHandle getResultHandle();
static jmethodID meth_getResultHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdGetLastCommittedTxnId
: virtual public JniProxy, virtual public ProxyDatabaseCmd, virtual public ProxyCsnHandleReturningCmd
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyCmdGetTxnCsn
: virtual public JniProxy, virtual public ProxyCsnHandleReturningCmd, virtual public ProxyTxnCmd
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyCmdInitiateBackup
: virtual public JniProxy, virtual public ProxyDatabaseCmd, virtual public ProxyCsnHandleReturningCmd
{
public:
std::string getBackupPathname();
static jmethodID meth_getBackupPathname;
bool isCheckSpaceRequirements();
static jmethodID meth_isCheckSpaceRequirements;
std::string getCompressionProgram();
static jmethodID meth_getCompressionProgram;
int64_t getLowerBoundCsn();
static jmethodID meth_getLowerBoundCsn;
int64_t getResultDataDeviceSize();
static jmethodID meth_getResultDataDeviceSize;
void setResultDataDeviceSize(const int64_t &valueRef);
void clearResultDataDeviceSize();
static jmethodID meth_setResultDataDeviceSize;
int64_t getSpacePadding();
static jmethodID meth_getSpacePadding;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdOpenDatabase
: virtual public JniProxy, virtual public ProxyCmd
{
public:
bool isCreateDatabase();
static jmethodID meth_isCreateDatabase;
SharedProxyDatabaseParam getParams();
static jmethodID meth_getParams;
SharedProxyDbHandle getResultHandle();
static jmethodID meth_getResultHandle;
bool isResultRecoveryRequired();
static jmethodID meth_isResultRecoveryRequired;
void setResultRecoveryRequired(const bool &valueRef);
void clearResultRecoveryRequired();
static jmethodID meth_setResultRecoveryRequired;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdPrepareExecutionStreamGraph
: virtual public JniProxy, virtual public ProxyTupleStreamGraphCmd
{
public:
int32_t getDegreeOfParallelism();
static jmethodID meth_getDegreeOfParallelism;
SharedProxyExecutionStreamDef getStreamDefs();
static jmethodID meth_getStreamDefs;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdRestoreFromBackup
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
std::string getBackupPathname();
static jmethodID meth_getBackupPathname;
std::string getCompressionProgram();
static jmethodID meth_getCompressionProgram;
int64_t getFileSize();
static jmethodID meth_getFileSize;
int64_t getLowerBoundCsn();
static jmethodID meth_getLowerBoundCsn;
int64_t getUpperBoundCsn();
static jmethodID meth_getUpperBoundCsn;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdRollback
: virtual public JniProxy, virtual public ProxyEndTxnCmd
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyCmdSavepoint
: virtual public JniProxy, virtual public ProxyTxnCmd
{
public:
SharedProxySvptHandle getResultHandle();
static jmethodID meth_getResultHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdSetParam
: virtual public JniProxy, virtual public ProxyDatabaseCmd
{
public:
SharedProxyDatabaseParam getParam();
static jmethodID meth_getParam;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdTruncateIndex
: virtual public JniProxy, virtual public ProxyCmdDropIndex
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyCmdVerifyIndex
: virtual public JniProxy, virtual public ProxyIndexAccessCmd
{
public:
bool isEstimate();
static jmethodID meth_isEstimate;
bool isIncludeTuples();
static jmethodID meth_isIncludeTuples;
int64_t getResultPageCount();
static jmethodID meth_getResultPageCount;
void setResultPageCount(const int64_t &valueRef);
void clearResultPageCount();
static jmethodID meth_setResultPageCount;
int64_t getResultUniqueKeyCount();
static jmethodID meth_getResultUniqueKeyCount;
void setResultUniqueKeyCount(const int64_t &valueRef);
void clearResultUniqueKeyCount();
static jmethodID meth_setResultUniqueKeyCount;
};

class FENNEL_FARRAGO_EXPORT ProxyCmdVersionIndexRoot
: virtual public JniProxy, virtual public ProxyTxnCmd
{
public:
int64_t getNewRootPageId();
static jmethodID meth_getNewRootPageId;
int64_t getOldRootPageId();
static jmethodID meth_getOldRootPageId;
};

class FENNEL_FARRAGO_EXPORT ProxyCollectTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyColumnName
: virtual public JniProxy
{
public:
SharedProxyFlatFileTupleStreamDef getFlatFile();
static jmethodID meth_getFlatFile;
std::string getName();
static jmethodID meth_getName;
};

class FENNEL_FARRAGO_EXPORT ProxyCorrelation
: virtual public JniProxy
{
public:
int32_t getId();
static jmethodID meth_getId;
SharedProxyIndexSearchDef getIndexSearch();
static jmethodID meth_getIndexSearch;
SharedProxyNestedLoopJoinStreamDef getNestedLoopJoin();
static jmethodID meth_getNestedLoopJoin;
int32_t getOffset();
static jmethodID meth_getOffset;
};

class FENNEL_FARRAGO_EXPORT ProxyCorrelationJoinStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
SharedProxyCorrelation getCorrelations();
static jmethodID meth_getCorrelations;
};

class FENNEL_FARRAGO_EXPORT ProxyHandle
: virtual public JniProxy
{
public:
int64_t getLongHandle();
static jmethodID meth_getLongHandle;
};

class FENNEL_FARRAGO_EXPORT ProxyCsnHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyDatabaseParam
: virtual public JniProxy
{
public:
std::string getName();
static jmethodID meth_getName;
std::string getValue();
static jmethodID meth_getValue;
};

class FENNEL_FARRAGO_EXPORT ProxyDbHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyDynamicParamUse
: virtual public JniProxy
{
public:
int32_t getDynamicParamId();
static jmethodID meth_getDynamicParamId;
SharedProxyExecutionStreamDef getExecutionStreamDef();
static jmethodID meth_getExecutionStreamDef;
bool isRead();
static jmethodID meth_isRead;
};

class FENNEL_FARRAGO_EXPORT ProxyDynamicParameter
: virtual public JniProxy
{
public:
SharedProxyBarrierStreamDef getBarrier();
static jmethodID meth_getBarrier;
int32_t getParameterId();
static jmethodID meth_getParameterId;
};

class FENNEL_FARRAGO_EXPORT ProxyExecStreamDataFlow
: virtual public JniProxy
{
public:
SharedProxyExecutionStreamDef getConsumer();
static jmethodID meth_getConsumer;
bool isImplicit();
static jmethodID meth_isImplicit;
SharedProxyExecutionStreamDef getProducer();
static jmethodID meth_getProducer;
};

class FENNEL_FARRAGO_EXPORT ProxyFlatFileTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
std::string getCalcProgram();
static jmethodID meth_getCalcProgram;
int32_t getCodePage();
static jmethodID meth_getCodePage;
SharedProxyColumnName getColumn();
static jmethodID meth_getColumn;
std::string getDataFilePath();
static jmethodID meth_getDataFilePath;
std::string getErrorFilePath();
static jmethodID meth_getErrorFilePath;
std::string getEscapeCharacter();
static jmethodID meth_getEscapeCharacter;
std::string getFieldDelimiter();
static jmethodID meth_getFieldDelimiter;
bool isHasHeader();
static jmethodID meth_isHasHeader;
bool isLenient();
static jmethodID meth_isLenient;
bool isMapped();
static jmethodID meth_isMapped;
int32_t getNumRowsScan();
static jmethodID meth_getNumRowsScan;
std::string getQuoteCharacter();
static jmethodID meth_getQuoteCharacter;
std::string getRowDelimiter();
static jmethodID meth_getRowDelimiter;
std::string getSubstituteCharacter();
static jmethodID meth_getSubstituteCharacter;
bool isTranslationRecovery();
static jmethodID meth_isTranslationRecovery;
bool isTrim();
static jmethodID meth_isTrim;
};

class FENNEL_FARRAGO_EXPORT ProxyGenericStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
std::string getContent();
static jmethodID meth_getContent;
std::string getType();
static jmethodID meth_getType;
};

class FENNEL_FARRAGO_EXPORT ProxyKeyAccessorDef
: virtual public JniProxy
{
public:
SharedProxyTupleProjection getKeyProj();
static jmethodID meth_getKeyProj;
};

class FENNEL_FARRAGO_EXPORT ProxyIndexAccessorDef
: virtual public JniProxy, virtual public ProxyKeyAccessorDef
{
public:
int64_t getIndexId();
static jmethodID meth_getIndexId;
bool isReadOnlyCommittedData();
static jmethodID meth_isReadOnlyCommittedData;
int32_t getRootPageIdParamId();
static jmethodID meth_getRootPageIdParamId;
int64_t getRootPageId();
static jmethodID meth_getRootPageId;
int64_t getSegmentId();
static jmethodID meth_getSegmentId;
SharedProxyTupleDescriptor getTupleDesc();
static jmethodID meth_getTupleDesc;
};

class FENNEL_FARRAGO_EXPORT ProxyIndexStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef, virtual public ProxyIndexAccessorDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyIndexLoaderDef
: virtual public JniProxy, virtual public ProxyIndexStreamDef
{
public:
Distinctness getDistinctness();
static jmethodID meth_getDistinctness;
bool isMonotonic();
static jmethodID meth_isMonotonic;
};

class FENNEL_FARRAGO_EXPORT ProxyIndexScanDef
: virtual public JniProxy, virtual public ProxyIndexStreamDef
{
public:
SharedProxyTupleProjection getOutputProj();
static jmethodID meth_getOutputProj;
};

class FENNEL_FARRAGO_EXPORT ProxyIndexSearchDef
: virtual public JniProxy, virtual public ProxyIndexScanDef
{
public:
SharedProxyTupleProjection getInputDirectiveProj();
static jmethodID meth_getInputDirectiveProj;
SharedProxyTupleProjection getInputJoinProj();
static jmethodID meth_getInputJoinProj;
SharedProxyTupleProjection getInputKeyProj();
static jmethodID meth_getInputKeyProj;
bool isOuterJoin();
static jmethodID meth_isOuterJoin;
bool isPrefetch();
static jmethodID meth_isPrefetch;
SharedProxyCorrelation getSearchKeyParameter();
static jmethodID meth_getSearchKeyParameter;
bool isUniqueKey();
static jmethodID meth_isUniqueKey;
};

class FENNEL_FARRAGO_EXPORT ProxyIndexWriterDef
: virtual public JniProxy, virtual public ProxyIndexAccessorDef
{
public:
Distinctness getDistinctness();
static jmethodID meth_getDistinctness;
SharedProxyTupleProjection getInputProj();
static jmethodID meth_getInputProj;
SharedProxyTableWriterDef getTableWriter();
static jmethodID meth_getTableWriter;
bool isUpdateInPlace();
static jmethodID meth_isUpdateInPlace;
};

class FENNEL_FARRAGO_EXPORT ProxyJavaSinkStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
int32_t getStreamId();
static jmethodID meth_getStreamId;
};

class FENNEL_FARRAGO_EXPORT ProxyJavaTransformStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
std::string getJavaClassName();
static jmethodID meth_getJavaClassName;
std::string getReserved();
static jmethodID meth_getReserved;
int32_t getStreamId();
static jmethodID meth_getStreamId;
};

class FENNEL_FARRAGO_EXPORT ProxyLbmBitOpStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
int32_t getRowLimitParamId();
static jmethodID meth_getRowLimitParamId;
int32_t getStartRidParamId();
static jmethodID meth_getStartRidParamId;
};

class FENNEL_FARRAGO_EXPORT ProxyLbmChopperStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
int32_t getRidLimitParamId();
static jmethodID meth_getRidLimitParamId;
};

class FENNEL_FARRAGO_EXPORT ProxyLcsRowScanStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
SharedProxyLcsClusterScanDef getClusterScan();
static jmethodID meth_getClusterScan;
bool isFullScan();
static jmethodID meth_isFullScan;
bool isHasExtraFilter();
static jmethodID meth_isHasExtraFilter;
SharedProxyTupleProjection getOutputProj();
static jmethodID meth_getOutputProj;
SharedProxyTupleProjection getResidualFilterColumns();
static jmethodID meth_getResidualFilterColumns;
int32_t getSamplingClumps();
static jmethodID meth_getSamplingClumps;
TableSamplingMode getSamplingMode();
static jmethodID meth_getSamplingMode;
float getSamplingRate();
static jmethodID meth_getSamplingRate;
int32_t getSamplingRepeatableSeed();
static jmethodID meth_getSamplingRepeatableSeed;
bool isSamplingRepeatable();
static jmethodID meth_isSamplingRepeatable;
int64_t getSamplingRowCount();
static jmethodID meth_getSamplingRowCount;
};

class FENNEL_FARRAGO_EXPORT ProxyLbmGeneratorStreamDef
: virtual public JniProxy, virtual public ProxyIndexAccessorDef, virtual public ProxyLcsRowScanStreamDef
{
public:
bool isCreateIndex();
static jmethodID meth_isCreateIndex;
int32_t getInsertRowCountParamId();
static jmethodID meth_getInsertRowCountParamId;
};

class FENNEL_FARRAGO_EXPORT ProxyLbmIntersectStreamDef
: virtual public JniProxy, virtual public ProxyLbmBitOpStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyLbmMinusStreamDef
: virtual public JniProxy, virtual public ProxyLbmBitOpStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyLbmNormalizerStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyLbmSearchStreamDef
: virtual public JniProxy, virtual public ProxyIndexSearchDef
{
public:
int32_t getRowLimitParamId();
static jmethodID meth_getRowLimitParamId;
int32_t getStartRidParamId();
static jmethodID meth_getStartRidParamId;
};

class FENNEL_FARRAGO_EXPORT ProxySortedAggStreamDef
: virtual public JniProxy, virtual public ProxyAggStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyLbmSortedAggStreamDef
: virtual public JniProxy, virtual public ProxySortedAggStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyLbmSplicerStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
bool isCreateNewIndex();
static jmethodID meth_isCreateNewIndex;
SharedProxySplicerIndexAccessorDef getIndexAccessor();
static jmethodID meth_getIndexAccessor;
int32_t getInsertRowCountParamId();
static jmethodID meth_getInsertRowCountParamId;
int32_t getWriteRowCountParamId();
static jmethodID meth_getWriteRowCountParamId;
};

class FENNEL_FARRAGO_EXPORT ProxyLbmUnionStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
int32_t getConsumerSridParamId();
static jmethodID meth_getConsumerSridParamId;
int32_t getRidLimitParamId();
static jmethodID meth_getRidLimitParamId;
int32_t getSegmentLimitParamId();
static jmethodID meth_getSegmentLimitParamId;
};

class FENNEL_FARRAGO_EXPORT ProxyLcsClusterAppendStreamDef
: virtual public JniProxy, virtual public ProxyIndexStreamDef
{
public:
SharedProxyTupleProjection getClusterColProj();
static jmethodID meth_getClusterColProj;
};

class FENNEL_FARRAGO_EXPORT ProxyLcsClusterReplaceStreamDef
: virtual public JniProxy, virtual public ProxyLcsClusterAppendStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyLcsClusterScanDef
: virtual public JniProxy, virtual public ProxyIndexAccessorDef
{
public:
SharedProxyTupleDescriptor getClusterTupleDesc();
static jmethodID meth_getClusterTupleDesc;
SharedProxyLcsRowScanStreamDef getRowScan();
static jmethodID meth_getRowScan;
};

class FENNEL_FARRAGO_EXPORT ProxyLhxAggStreamDef
: virtual public JniProxy, virtual public ProxyAggStreamDef
{
public:
int64_t getCndGroupByKeys();
static jmethodID meth_getCndGroupByKeys;
int64_t getNumRows();
static jmethodID meth_getNumRows;
};

class FENNEL_FARRAGO_EXPORT ProxyLhxJoinStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
int64_t getCndBuildKeys();
static jmethodID meth_getCndBuildKeys;
SharedProxyTupleProjection getFilterNullProj();
static jmethodID meth_getFilterNullProj;
bool isLeftInner();
static jmethodID meth_isLeftInner;
SharedProxyTupleProjection getLeftKeyProj();
static jmethodID meth_getLeftKeyProj;
bool isLeftOuter();
static jmethodID meth_isLeftOuter;
int64_t getNumBuildRows();
static jmethodID meth_getNumBuildRows;
bool isRightInner();
static jmethodID meth_isRightInner;
SharedProxyTupleProjection getRightKeyProj();
static jmethodID meth_getRightKeyProj;
bool isRightOuter();
static jmethodID meth_isRightOuter;
bool isSetopAll();
static jmethodID meth_isSetopAll;
bool isSetopDistinct();
static jmethodID meth_isSetopDistinct;
};

class FENNEL_FARRAGO_EXPORT ProxyMergeStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
bool isPrePullInputs();
static jmethodID meth_isPrePullInputs;
bool isSequential();
static jmethodID meth_isSequential;
};

class FENNEL_FARRAGO_EXPORT ProxyMockTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
int64_t getRowCount();
static jmethodID meth_getRowCount;
};

class FENNEL_FARRAGO_EXPORT ProxyNestedLoopJoinStreamDef
: virtual public JniProxy, virtual public ProxyCartesianProductStreamDef
{
public:
SharedProxyCorrelation getLeftJoinKey();
static jmethodID meth_getLeftJoinKey;
};

class FENNEL_FARRAGO_EXPORT ProxyReshapeParameter
: virtual public JniProxy
{
public:
int32_t getCompareOffset();
static jmethodID meth_getCompareOffset;
int32_t getDynamicParamId();
static jmethodID meth_getDynamicParamId;
bool isOutputParam();
static jmethodID meth_isOutputParam;
SharedProxyReshapeStreamDef getReshape();
static jmethodID meth_getReshape;
};

class FENNEL_FARRAGO_EXPORT ProxyReshapeStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
CompOperator getCompareOp();
static jmethodID meth_getCompareOp;
SharedProxyTupleProjection getInputCompareProjection();
static jmethodID meth_getInputCompareProjection;
SharedProxyTupleProjection getOutputProjection();
static jmethodID meth_getOutputProjection;
SharedProxyReshapeParameter getReshapeParameter();
static jmethodID meth_getReshapeParameter;
std::string getTupleCompareBytesBase64();
static jmethodID meth_getTupleCompareBytesBase64;
};

class FENNEL_FARRAGO_EXPORT ProxySortingStreamDef
: virtual public JniProxy, virtual public ProxyKeyAccessorDef, virtual public ProxyTupleStreamDef
{
public:
SharedProxyTupleProjection getDescendingProj();
static jmethodID meth_getDescendingProj;
Distinctness getDistinctness();
static jmethodID meth_getDistinctness;
bool isEarlyClose();
static jmethodID meth_isEarlyClose;
int64_t getEstimatedNumRows();
static jmethodID meth_getEstimatedNumRows;
};

class FENNEL_FARRAGO_EXPORT ProxySplicerIndexAccessorDef
: virtual public JniProxy, virtual public ProxyIndexAccessorDef
{
public:
SharedProxyLbmSplicerStreamDef getSplicer();
static jmethodID meth_getSplicer;
};

class FENNEL_FARRAGO_EXPORT ProxySplitterStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyStreamGraphHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyStreamHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxySvptHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyTableWriterDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
SharedProxyIndexWriterDef getIndexWriter();
static jmethodID meth_getIndexWriter;
};

class FENNEL_FARRAGO_EXPORT ProxyTableDeleterDef
: virtual public JniProxy, virtual public ProxyTableWriterDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyTableInserterDef
: virtual public JniProxy, virtual public ProxyTableWriterDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyTableUpdaterDef
: virtual public JniProxy, virtual public ProxyTableWriterDef
{
public:
SharedProxyTupleProjection getUpdateProj();
static jmethodID meth_getUpdateProj;
};

class FENNEL_FARRAGO_EXPORT ProxyTupleAccessor
: virtual public JniProxy
{
public:
SharedProxyTupleAttrAccessor getAttrAccessor();
static jmethodID meth_getAttrAccessor;
int32_t getBitFieldOffset();
static jmethodID meth_getBitFieldOffset;
int32_t getMinByteLength();
static jmethodID meth_getMinByteLength;
};

class FENNEL_FARRAGO_EXPORT ProxyTupleAttrAccessor
: virtual public JniProxy
{
public:
int32_t getBitValueIndex();
static jmethodID meth_getBitValueIndex;
int32_t getEndIndirectOffset();
static jmethodID meth_getEndIndirectOffset;
int32_t getFixedOffset();
static jmethodID meth_getFixedOffset;
int32_t getNullBitIndex();
static jmethodID meth_getNullBitIndex;
};

class FENNEL_FARRAGO_EXPORT ProxyTupleAttrDescriptor
: virtual public JniProxy
{
public:
int32_t getByteLength();
static jmethodID meth_getByteLength;
bool isNullable();
static jmethodID meth_isNullable;
int32_t getTypeOrdinal();
static jmethodID meth_getTypeOrdinal;
};

class FENNEL_FARRAGO_EXPORT ProxyTupleAttrProjection
: virtual public JniProxy
{
public:
int32_t getAttributeIndex();
static jmethodID meth_getAttributeIndex;
};

class FENNEL_FARRAGO_EXPORT ProxyTupleDescriptor
: virtual public JniProxy
{
public:
SharedProxyTupleAttrDescriptor getAttrDescriptor();
static jmethodID meth_getAttrDescriptor;
};

class FENNEL_FARRAGO_EXPORT ProxyTupleProjection
: virtual public JniProxy
{
public:
SharedProxyTupleAttrProjection getAttrProjection();
static jmethodID meth_getAttrProjection;
};

class FENNEL_FARRAGO_EXPORT ProxyTxnHandle
: virtual public JniProxy, virtual public ProxyHandle
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyUncollectTupleStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
};

class FENNEL_FARRAGO_EXPORT ProxyValuesStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
std::string getTupleBytesBase64();
static jmethodID meth_getTupleBytesBase64;
};

class FENNEL_FARRAGO_EXPORT ProxyWindowDef
: virtual public JniProxy
{
public:
int32_t getOffset();
static jmethodID meth_getOffset;
SharedProxyTupleProjection getOrderKeyList();
static jmethodID meth_getOrderKeyList;
SharedProxyWindowPartitionDef getPartition();
static jmethodID meth_getPartition;
bool isPhysical();
static jmethodID meth_isPhysical;
std::string getRange();
static jmethodID meth_getRange;
SharedProxyWindowStreamDef getWindowStream();
static jmethodID meth_getWindowStream;
};

class FENNEL_FARRAGO_EXPORT ProxyWindowPartitionDef
: virtual public JniProxy
{
public:
std::string getAddProgram();
static jmethodID meth_getAddProgram;
SharedProxyTupleDescriptor getBucketDesc();
static jmethodID meth_getBucketDesc;
std::string getDropProgram();
static jmethodID meth_getDropProgram;
std::string getInitializeProgram();
static jmethodID meth_getInitializeProgram;
SharedProxyTupleProjection getPartitionKeyList();
static jmethodID meth_getPartitionKeyList;
SharedProxyWindowDef getWindow();
static jmethodID meth_getWindow;
};

class FENNEL_FARRAGO_EXPORT ProxyWindowStreamDef
: virtual public JniProxy, virtual public ProxyTupleStreamDef
{
public:
bool isFilter();
static jmethodID meth_isFilter;
SharedProxyTupleProjection getInputOrderKeyList();
static jmethodID meth_getInputOrderKeyList;
std::string getOutputProgram();
static jmethodID meth_getOutputProgram;
SharedProxyWindowDef getWindow();
static jmethodID meth_getWindow;
};

class FENNEL_FARRAGO_EXPORT FemVisitor : virtual public JniProxyVisitor
{
public:
static JniProxyVisitTable<FemVisitor> visitTbl;
virtual void visit(ProxyAggInvocation &)
{ unhandledVisit(); }
virtual void visit(ProxyAggStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyBarrierStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyBeginTxnCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyBernoulliSamplingStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyBufferReaderStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyBufferWriterStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyBufferingTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyCalcTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyCartesianProductStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdAbandonBackup &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdAlterSystemDeallocate &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdBeginTxn &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdBeginTxnWithCsn &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCheckpoint &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCloseDatabase &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCommit &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCompleteBackup &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCreateExecutionStreamGraph &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCreateIndex &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdCreateStreamHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdDropIndex &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdGetLastCommittedTxnId &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdGetTxnCsn &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdInitiateBackup &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdOpenDatabase &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdPrepareExecutionStreamGraph &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdRestoreFromBackup &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdRollback &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdSavepoint &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdSetParam &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdTruncateIndex &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdVerifyIndex &)
{ unhandledVisit(); }
virtual void visit(ProxyCmdVersionIndexRoot &)
{ unhandledVisit(); }
virtual void visit(ProxyCollectTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyColumnName &)
{ unhandledVisit(); }
virtual void visit(ProxyCorrelation &)
{ unhandledVisit(); }
virtual void visit(ProxyCorrelationJoinStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyCsnHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyCsnHandleReturningCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyDatabaseCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyDatabaseParam &)
{ unhandledVisit(); }
virtual void visit(ProxyDbHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyDynamicParamUse &)
{ unhandledVisit(); }
virtual void visit(ProxyDynamicParameter &)
{ unhandledVisit(); }
virtual void visit(ProxyEndTxnCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyExecStreamDataFlow &)
{ unhandledVisit(); }
virtual void visit(ProxyExecutionStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyFlatFileTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyGenericStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexAccessCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexAccessorDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexLoaderDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexScanDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexSearchDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyIndexWriterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyJavaSinkStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyJavaTransformStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyKeyAccessorDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmBitOpStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmChopperStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmGeneratorStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmIntersectStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmMinusStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmNormalizerStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmSearchStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmSortedAggStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmSplicerStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLbmUnionStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLcsClusterAppendStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLcsClusterReplaceStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLcsClusterScanDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLcsRowScanStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLhxAggStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyLhxJoinStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyMergeStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyMockTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyMultiUseBufferingStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyNestedLoopJoinStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyReshapeParameter &)
{ unhandledVisit(); }
virtual void visit(ProxyReshapeStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxySortedAggStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxySortingStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxySplicerIndexAccessorDef &)
{ unhandledVisit(); }
virtual void visit(ProxySplitterStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyStreamGraphHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyStreamHandle &)
{ unhandledVisit(); }
virtual void visit(ProxySvptHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyTableDeleterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTableInserterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTableUpdaterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTableWriterDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleAccessor &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleAttrAccessor &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleAttrDescriptor &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleAttrProjection &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleDescriptor &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleProjection &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyTupleStreamGraphCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyTxnCmd &)
{ unhandledVisit(); }
virtual void visit(ProxyTxnHandle &)
{ unhandledVisit(); }
virtual void visit(ProxyUncollectTupleStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyValuesStreamDef &)
{ unhandledVisit(); }
virtual void visit(ProxyWindowDef &)
{ unhandledVisit(); }
virtual void visit(ProxyWindowPartitionDef &)
{ unhandledVisit(); }
virtual void visit(ProxyWindowStreamDef &)
{ unhandledVisit(); }
};

