/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_farrago_fennel_FennelPseudoUuidGenerator */

#ifndef _Included_net_sf_farrago_fennel_FennelPseudoUuidGenerator
#define _Included_net_sf_farrago_fennel_FennelPseudoUuidGenerator
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
#undef net_sf_farrago_fennel_FennelPseudoUuidGenerator_UUID_LENGTH
#define net_sf_farrago_fennel_FennelPseudoUuidGenerator_UUID_LENGTH 16L
/* Inaccessible static: class_00024net_00024sf_00024farrago_00024fennel_00024FennelPseudoUuidGenerator */
/*
 * Class:     net_sf_farrago_fennel_FennelPseudoUuidGenerator
 * Method:    nativeGenerate
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sf_farrago_fennel_FennelPseudoUuidGenerator_nativeGenerate
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_farrago_fennel_FennelPseudoUuidGenerator
 * Method:    nativeGenerateInvalid
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sf_farrago_fennel_FennelPseudoUuidGenerator_nativeGenerateInvalid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
