/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_farrago_fennel_FennelStorage */

#ifndef _Included_net_sf_farrago_fennel_FennelStorage
#define _Included_net_sf_farrago_fennel_FennelStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    newObjectHandle
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_farrago_fennel_FennelStorage_newObjectHandle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    deleteObjectHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_farrago_fennel_FennelStorage_deleteObjectHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    setObjectHandle
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_net_sf_farrago_fennel_FennelStorage_setObjectHandle
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    getHandleCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_farrago_fennel_FennelStorage_getHandleCount
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    getAccessorXmiForTupleDescriptor
 * Signature: (Lnet/sf/farrago/fem/fennel/FemTupleDescriptor;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_farrago_fennel_FennelStorage_getAccessorXmiForTupleDescriptor
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    executeJavaCmd
 * Signature: (Lnet/sf/farrago/fem/fennel/FemCmd;)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_farrago_fennel_FennelStorage_executeJavaCmd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    tupleStreamOpen
 * Signature: (Lnet/sf/farrago/fem/fennel/FemStreamHandle;Lnet/sf/farrago/fem/fennel/FemTxnHandle;Lnet/sf/farrago/fennel/FennelJavaStreamMap;)V
 */
JNIEXPORT void JNICALL Java_net_sf_farrago_fennel_FennelStorage_tupleStreamOpen
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    tupleStreamFetch
 * Signature: (Lnet/sf/farrago/fem/fennel/FemStreamHandle;[B)I
 */
JNIEXPORT jint JNICALL Java_net_sf_farrago_fennel_FennelStorage_tupleStreamFetch
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     net_sf_farrago_fennel_FennelStorage
 * Method:    tupleStreamClose
 * Signature: (Lnet/sf/farrago/fem/fennel/FemStreamHandle;Z)V
 */
JNIEXPORT void JNICALL Java_net_sf_farrago_fennel_FennelStorage_tupleStreamClose
  (JNIEnv *, jclass, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
