-- Query 2
@PLAN@
SELECT AL3.SRVPLN_KEY, AL3.SRVPLN_ID,
 AL3.SRVPLN_NM, AL3.SPO_ID, AL3.SPO_NM,
 AL3.BU_CD, AL3.RC_CD, AL3.PROC_BAT_ID,
 AL4.REVN_YR_MO, AVG(AL5.USG_DAYS_NUM),
 AVG(AL5.RSD_SVC_BILG_AMT), AVG(AL5.USGC_BILL_KW_VAL),
 AVG(AL5.USG_BILL_KWH), AVG(AL5.RSD_DMND_CHRG_AMT),
 AVG(AL5.RSD_CUST_CHRG_AMT), AVG(AL5.RSD_CCOGC_AMT),
 AVG(AL5.RSD_CCOGA_AMT), AVG(AL5.RSD_TOP_SRCHRG_AMT),
 AVG(AL5.RSD_BALG_CHRG_AMT), AVG(AL5.RSD_ST_SLSTX_AMT),
 AVG(AL5.RSD_TRSPT_CHRG_AMT)
FROM
--  PGE.CUST_SERV_ACCT AL1,
--  PGE.GEOG AL2,
--  PGE.SERV_PLAN AL3,
--  PGE.REVN_PRD AL4,
--  PGE.REVN_DTL_RAND AL5
 PGE.REVN_DTL_RAND AL5,
 PGE.CUST_SERV_ACCT AL1,
 PGE.SERV_PLAN AL3,
 PGE.GEOG AL2,
 PGE.REVN_PRD AL4
WHERE (AL5.REVN_YR_MO=AL4.REVN_YR_MO
 AND AL2.GEOG_KEY=AL5.GEOG_KEY AND AL3.SRVPLN_KEY=AL5.SRVPLN_KEY
 AND AL1.CUST_SERV_ACCT_KEY=AL5.CUST_SERV_ACCT_KEY)  AND
 (AL2.ST_CD='IN' AND AL2.GEOG_CNTY_DESC='LAPORTE'
 AND AL2.RVTWN_DESC='LA PORTE' AND AL4.REVN_YR=1995
 AND AL3.SPO_NM='ELE SPACE HEAT - RES'
 AND AL3.SRVPLN_NM='ELEC - RESIDENTIAL')
GROUP BY AL3.SRVPLN_KEY, AL3.SRVPLN_ID,
 AL3.SRVPLN_NM, AL3.SPO_ID, AL3.SPO_NM,
 AL3.BU_CD, AL3.RC_CD, AL3.PROC_BAT_ID, AL4.REVN_YR_MO
ORDER BY 13 
;
