-- Query 20b
SELECT DISTINCT AL1.IS_DWLGS_VAL, AL1.CU_ID, AL1.CUOR_CUST_NM,
AL1.CUIN_LST_NM, AL2.SRVPLN_ID
 FROM PGE.CUST_SERV_ACCT AL1 LEFT OUTER JOIN pge.revn_dtl_rand AL3
        ON AL1.CUST_SERV_ACCT_KEY = AL3.CUST_SERV_ACCT_KEY,
  PGE.SERV_PLAN AL2
 WHERE
        AL3.SRVPLN_KEY = AL2.SRVPLN_KEY 
  AND   AL1.IS_DWLGS_VAL = 1
  AND   AL3.rsd_svc_bilg_amt > 1000
 ORDER BY 1,2,3,4,5
;
