-- Query 9
@PLAN@
SELECT AL2.ST_CD, AL2.GEOG_CNTY_DESC, AL2.RVTWN_DESC,
 AL3.SRVPLN_ID, AL3.SRVPLN_NM, AL3.SPO_ID, AL3.SPO_NM,
 COUNT(AL1.CU_ID)
FROM
 PGE.REVN_DTL_RAND AL5,
 PGE.CUST_SERV_ACCT AL1,
 PGE.SERV_PLAN AL3,
 PGE.GEOG AL2,
 PGE.REVN_PRD AL4
--  PGE.CUST_SERV_ACCT AL1,
--  PGE.GEOG AL2,
--  PGE.SERV_PLAN AL3,
--  PGE.REVN_PRD AL4,
--  PGE.REVN_DTL_RAND AL5
WHERE (AL5.REVN_YR_MO=AL4.REVN_YR_MO
 AND AL2.GEOG_KEY=AL5.GEOG_KEY
 AND AL3.SRVPLN_KEY=AL5.SRVPLN_KEY
 AND AL1.CUST_SERV_ACCT_KEY=AL5.CUST_SERV_ACCT_KEY)
GROUP by  AL2.ST_CD, AL2.GEOG_CNTY_DESC, AL2.RVTWN_DESC,
 AL3.SRVPLN_ID, AL3.SRVPLN_NM, AL3.SPO_ID, AL3.SPO_NM
ORDER BY  2,3,4,5,7,8
;
