-- Query 10
@PLAN@
SELECT AL1.CU_ID, AL1.CUOR_CUST_NM, AL1.CUIN_LST_NM, AL1.ST_CD,
 AL1.ZIP_CD_NUM, AL1.CO_CD, AL1.IS_DWLGS_VAL, AL3.SRVPLN_ID,
 AL3.SRVPLN_NM, AVG(AL5.USG_VAL), AVG(AL5.USG_BILL_THERM),
 AVG(AL5.RSD_SVC_BILG_AMT)
FROM
 PGE.CUST_SERV_ACCT AL1,
 PGE.GEOG AL2,
 PGE.SERV_PLAN AL3,
 PGE.REVN_PRD AL4,
 PGE.REVN_DTL_RAND AL5
WHERE (AL5.REVN_YR_MO=AL4.REVN_YR_MO
 AND AL2.GEOG_KEY=AL5.GEOG_KEY AND AL3.SRVPLN_KEY=AL5.SRVPLN_KEY
 AND AL1.CUST_SERV_ACCT_KEY=AL5.CUST_SERV_ACCT_KEY)
 AND (AL4.REVN_YR_MO=
  (SELECT max(AL4.REVN_YR_MO) FROM PGE.REVN_PRD AL4)
 AND AL1.IS_DWLGS_VAL>1 AND AL3.SRVPLN_NM LIKE '%MULT%')
GROUP BY AL1.CU_ID, AL1.CUOR_CUST_NM, AL1.CUIN_LST_NM, AL1.ST_CD,
 AL1.ZIP_CD_NUM, AL1.CO_CD, AL1.IS_DWLGS_VAL, AL3.SRVPLN_ID,
 AL3.SRVPLN_NM
ORDER BY  7 DESC, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12
;

