-- Query 12
@PLAN@
SELECT AL4.REVN_YR_MO, AL1.CU_ID, AL3.SRVPLN_ID,
 AL3.SRVPLN_NM, AL3.SPO_ID, AL3.SPO_NM, AL3.BU_CD,
 AL3.RC_CD, AL1.CUOR_CUST_NM, AL1.CUIN_LST_NM,
 AL1.CUIN_FST_NM, AL1.MAIL_ADDR_ID
FROM
 PGE.CUST_SERV_ACCT AL1,
 PGE.GEOG AL2,
 PGE.SERV_PLAN AL3,
 PGE.REVN_PRD AL4,
 PGE.REVN_DTL_RAND AL5
WHERE (AL5.REVN_YR_MO=AL4.REVN_YR_MO
 AND AL2.GEOG_KEY=AL5.GEOG_KEY AND AL3.SRVPLN_KEY=AL5.SRVPLN_KEY
 AND AL1.CUST_SERV_ACCT_KEY=AL5.CUST_SERV_ACCT_KEY)
 AND (AL5.SAS_FNL_BIL_INDCR='Y')
 AND (AL4.REVN_YR_MO=
  (select max(AL4.REVN_YR_MO) FROM PGE.REVN_PRD AL4))
GROUP BY AL4.REVN_YR_MO, AL1.CU_ID, AL3.SRVPLN_ID,
 AL3.SRVPLN_NM, AL3.SPO_ID, AL3.SPO_NM, AL3.BU_CD,
 AL3.RC_CD, AL1.CUOR_CUST_NM, AL1.CUIN_LST_NM, AL1.CUIN_FST_NM,
 AL1.MAIL_ADDR_ID
ORDER BY 2, 3
;
