-- Query 16
@PLAN@
SELECT AL1.SRVPLN_ID, AL1.SRVPLN_NM,
 SUM(AL2.RSD_SVC_BILG_AMT)
FROM
 PGE.SERV_PLAN AL1,
 PGE.REVN_DTL_RAND AL2
WHERE (AL1.SRVPLN_KEY=AL2.SRVPLN_KEY)
GROUP BY AL1.SRVPLN_ID, AL1.SRVPLN_NM
ORDER BY  3 DESC
;
