-- Query 18
@PLAN@
SELECT AL2.RVTWN_DESC, AL4.REVN_QTR, AL3.SRVPLN_ID,
 AL3.SRVPLN_NM, SUM(AL5.USG_VAL), SUM(AL5.USG_BILL_THERM),
 SUM(AL5.RSD_SVC_BILG_AMT)
FROM
 PGE.CUST_SERV_ACCT AL1,
 PGE.GEOG AL2,
 PGE.SERV_PLAN AL3,
 PGE.REVN_PRD AL4,
 PGE.REVN_DTL_RAND AL5
WHERE (AL5.REVN_YR_MO=AL4.REVN_YR_MO
 AND AL2.GEOG_KEY=AL5.GEOG_KEY AND AL3.SRVPLN_KEY=AL5.SRVPLN_KEY
 AND AL1.CUST_SERV_ACCT_KEY=AL5.CUST_SERV_ACCT_KEY)
 AND (AL4.REVN_YR=1995 AND AL3.SRVPLN_NM LIKE '%RESIDENTIAL%'
 AND AL2.ST_CD='IN' AND AL2.GEOG_CNTY_DESC='LAPORTE'
 AND AL5.RSD_CU_CNT=1)
GROUP BY AL2.RVTWN_DESC, AL4.REVN_QTR,
 AL3.SRVPLN_ID, AL3.SRVPLN_NM
ORDER BY  2, 1, 3, 4, 5, 6, 7
;
