-- Query 3
SELECT AL3.SRVPLN_ID, AL3.SRVPLN_NM,
 AL3.RC_CD, AL3.RC_DESC, AL4.REVN_YR_MO,
 AVG(AL5.USG_VAL), AVG(AL5.USG_BILL_THERM),
 AVG(AL5.RSD_SVC_BILG_AMT)
FROM
 PGE.CUST_SERV_ACCT AL1,
 PGE.GEOG AL2,
 PGE.SERV_PLAN AL3,
 PGE.REVN_PRD AL4,
 PGE.REVN_DTL_RAND AL5
WHERE (AL5.REVN_YR_MO=AL4.REVN_YR_MO
 AND AL2.GEOG_KEY=AL5.GEOG_KEY AND AL3.SRVPLN_KEY=AL5.SRVPLN_KEY
 AND AL1.CUST_SERV_ACCT_KEY=AL5.CUST_SERV_ACCT_KEY)
 AND (AL3.SRVPLN_NM='GAS - MULT FAMILY HOUSING'
 AND AL3.SPO_ID=1
 AND AL3.RC_DESC='MULTIPLE DWELLING - G''NRL SERV'
 AND AL4.REVN_YR=1995)
GROUP BY AL3.SRVPLN_ID,
 AL3.SRVPLN_NM, AL3.RC_CD, AL3.RC_DESC, AL4.REVN_YR_MO
ORDER BY 5,6,7,8
;
