-- Query 4
SELECT AL4.REVN_YR_MO, AL2.GEOG_CNTY_CD, AL2.GEOG_CNTY_DESC,
 AL2.RVTWN_CD, AL2.RVTWN_DESC, COUNT(AL1.CU_ID)
FROM
 PGE.CUST_SERV_ACCT AL1,
 PGE.GEOG AL2,
 PGE.SERV_PLAN AL3,
 PGE.REVN_PRD AL4,
 PGE.REVN_DTL_RAND AL5
WHERE (AL5.REVN_YR_MO=AL4.REVN_YR_MO AND AL2.GEOG_KEY=AL5.GEOG_KEY
 AND AL3.SRVPLN_KEY=AL5.SRVPLN_KEY AND
 AL1.CUST_SERV_ACCT_KEY=AL5.CUST_SERV_ACCT_KEY)
 AND (AL5.SAS_FNL_BIL_INDCR='Y')
GROUP BY AL4.REVN_YR_MO, AL2.GEOG_CNTY_CD, AL2.GEOG_CNTY_DESC,
 AL2.RVTWN_CD, AL2.RVTWN_DESC
ORDER BY 5, 1, 6
;
