-- CUST_SERV_ACCT
-- create unique index I_CSA_PRIME on PGE.CUST_SERV_ACCT (CUST_SERV_ACCT_KEY);
create index I_CSA_PRIME on PGE.CUST_SERV_ACCT (CUST_SERV_ACCT_KEY);
create index I_CSA_IS_DWLGS_VAL on PGE.CUST_SERV_ACCT (IS_DWLGS_VAL);

-- GEOG
-- create unique index I_GEOG_PRIME on PGE.GEOG (GEOG_KEY);
create index I_GEOG_PRIME on PGE.GEOG (GEOG_KEY);

-- REVN_PRD
-- create unique index I_REVN_PRD_PRIME on PGE.REVN_PRD (REVN_YR_MO);
create index I_REVN_PRD_PRIME on PGE.REVN_PRD (REVN_YR_MO);

-- SERV_PLAN
-- create unique index I_SERV_PLAN_PRIME on PGE.SERV_PLAN (SRVPLN_KEY);
create index I_SERV_PLAN_PRIME on PGE.SERV_PLAN (SRVPLN_KEY);

-- REVN_DTL_RAND
create index I_FACT_REVN_YR_MO on PGE.REVN_DTL_RAND (REVN_YR_MO);
create index I_FACT_GEOG_KEY on PGE.REVN_DTL_RAND (GEOG_KEY);
create index I_FACT_SRVPLN_KEY on PGE.REVN_DTL_RAND (SRVPLN_KEY);
create index I_FACT_CUST_SERV_ACCT_KEY on PGE.REVN_DTL_RAND (CUST_SERV_ACCT_KEY);

create index I_FACT_RSD_SVC_BILG_AMT on PGE.REVN_DTL_RAND (RSD_SVC_BILG_AMT);
-- End createi.sql
