#!/bin/bash
# $Id$
# Run the hsqldb Database Manager tool as a client
# to a Farrago server

source ./defineFarragoRuntime.sh

java ${CLIENT_JAVA_ARGS} org.hsqldb.util.DatabaseManagerSwing \
--driver net.sf.farrago.jdbc.client.FarragoJdbcClientDriver \
--url jdbc:farrago:rmi://localhost \
--user sa \
$*
