#!/bin/bash
# $Id$
# Run a single Junit test case from the default test package

if [ ! "$1" ]; then 
   echo "Error: specify a .sql filename or an unqualified test class name"; 
   exit; 
fi

SCRIPT_DIR=$(cd `dirname $0`; echo $PWD)

$SCRIPT_DIR/junitSingle "$1" jswat.junit
