#!/bin/bash
# $Id$
# Run the sqlline command-line SQL interpreter 
# with an embedded Farrago engine

source ./defineFarragoRuntime.sh

if java ${SERVER_JAVA_ARGS} ${SQLLINE_JAVA_ARGS} \
    -u jdbc:farrago: -d net.sf.farrago.jdbc.engine.FarragoJdbcEngineDriver \
    -n sa $*;
then
    echo
else
    tset
    echo "Terminal reset because sqlline crashed"
fi

