#!/bin/bash
# $Id: //open/farrago/sqlline#4 $
# Run the sqlline command-line SQL interpreter as a client
# to a Farrago server

source ./defineFarragoRuntime.sh

java ${CLIENT_JAVA_ARGS} ${SQLLINE_JAVA_ARGS} \
    -u jdbc:farrago:rmi://localhost \
    -d net.sf.farrago.jdbc.client.FarragoJdbcClientDriver \
    -n guest $*
