/*
// Farrago is a relational database management system.
// Copyright (C) 2003-2004 John V. Sichi.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 2.1
// of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

package net.sf.farrago.db;

import net.sf.farrago.session.*;
import net.sf.farrago.fem.fennel.*;

/**
 * FarragoDbSavepoint implements the {@link
 * net.sf.farrago.session.FarragoSessionSavepoint} interface in terms of a
 * {@link FarragoDbSession}.
 *
 * @author John V. Sichi
 * @version $Id$
 */
class FarragoDbSavepoint implements FarragoSessionSavepoint
{
    /**
     * Session which created this savepoint.
     */
    FarragoDbSession session;
    
    /**
     * ID generated by session (unique within session scope).
     */
    private int id;

    /**
     * Name assigned by user, or null if unnamed.
     */
    private String name;

    /**
     * Handle to underlying Fennel savepoint.
     */
    private FemSvptHandle femSvptHandle;

    FarragoDbSavepoint(
        int id,String name,FemSvptHandle femSvptHandle,FarragoDbSession session)
    {
        this.id = id;
        this.name = name;
        this.femSvptHandle = femSvptHandle;
        this.session = session;
    }
    
    // implement FarragoSessionSavepoint
    public int getId()
    {
        return id;
    }

    // implement FarragoSessionSavepoint
    public String getName()
    {
        return name;
    }

    // implement Object
    public boolean equals(Object obj)
    {
        if (!(obj instanceof FarragoDbSavepoint)) {
            return false;
        }
        FarragoDbSavepoint other = (FarragoDbSavepoint) obj;
        return (id == other.id) && (session == other.session);
    }

    // implement Object
    public int hashCode()
    {
        return id;
    }

    FemSvptHandle getFemSvptHandle()
    {
        return femSvptHandle;
    }
}

// End FarragoDbSavepoint.java
