#!/bin/bash
# $Id$
# Run the hsqldb Database Manager tool
# with an embedded LucidDB engine

source ./defineLucidDbRuntime.sh

java ${SERVER_JAVA_ARGS} org.hsqldb.util.DatabaseManagerSwing \
--driver com.lucidera.jdbc.LucidDbLocalDriver \
--url jdbc:luciddb: \
--user sa \
$*
