#!/bin/bash
# $Id$
# Run the sqlline command-line SQL interpreter as a client
# to a LucidDB server

source ./defineLucidDbRuntime.sh

java ${CLIENT_JAVA_ARGS} ${SQLLINE_JAVA_ARGS} \
    -u jdbc:luciddb:http://localhost \
    -d org.luciddb.jdbc.LucidDbClientDriver \
    -n sa $*
