SELECT COUNT(*) FROM BENCH1M 
WHERE KSEQ = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K100K = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K10K = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K1K = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K100 = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K25 = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K10 = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K5 = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K4 = 2
;
SELECT COUNT(*) FROM BENCH1M
WHERE K2 = 2
;
