-- TPC-D Parameter Substitution (Version 1.1.0D)
-- using default substitutions

set schema 'tpch';

SELECT
    PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VAL
FROM
    PARTSUPP, SUPPLIER, NATION,
    (SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000000 AS TMP
     FROM PARTSUPP, SUPPLIER, NATION
     WHERE PS_SUPPKEY = S_SUPPKEY AND
           S_NATIONKEY = N_NATIONKEY AND
           N_NAME = 'GERMANY') AS TEMPS
WHERE 
    PS_SUPPKEY = S_SUPPKEY AND 
    S_NATIONKEY = N_NATIONKEY AND
    N_NAME = 'GERMANY'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST*PS_AVAILQTY) > SUM(TEMPS.TMP)/COUNT(*)
ORDER BY VAL;
-- ORDER BY VAL DESC;
