-- Q15 (tpch2.6.1)

CREATE VIEW TPCH.REVENUE0 (SUPPLIER_NO, TOTAL_REVENUE) AS
    SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
    FROM TPCH.LINEITEM
    WHERE
        L_SHIPDATE >= DATE'1996-01-01' AND
        L_SHIPDATE < DATE'1996-04-01'
    GROUP BY L_SUPPKEY;

--
-- rewritten query before subquery support
--
--SELECT S_SUPPKEY, S_NAME, S_ADDRESS,  S_PHONE, TOTAL_REVENUE
--FROM SUPPLIER, REVENUE0,
--     (SELECT MAX(TOTAL_REVENUE) AS MAXREV FROM REVENUE0) AS TEMP
--WHERE S_SUPPKEY = SUPPLIER_NO AND
--      TOTAL_REVENUE = TEMP.MAXREV
--ORDER BY S_SUPPKEY;

SELECT
    S_SUPPKEY,
    S_NAME,
    S_ADDRESS,
    S_PHONE,
    TOTAL_REVENUE
FROM
    TPCH.SUPPLIER,
    TPCH.REVENUE0
WHERE
    S_SUPPKEY = SUPPLIER_NO
    AND TOTAL_REVENUE = (
        SELECT
            MAX(TOTAL_REVENUE)
        FROM
            TPCH.REVENUE0
    )
ORDER BY
    S_SUPPKEY;

DROP VIEW TPCH.REVENUE0;

