-- TPC-D Parameter Substitution (Version 1.1.0D)
-- using default substitutions

set schema 'tpch';

CREATE VIEW REVENUE0 (SUPPLIER_NO, TOTAL_REVENUE) AS
    SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
    FROM LINEITEM
    WHERE
        L_SHIPDATE >= DATE'1996-01-01' AND
        L_SHIPDATE < DATE'1996-04-01'
    GROUP BY L_SUPPKEY;


SELECT S_SUPPKEY, S_NAME, S_ADDRESS,  S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE0,
     (SELECT MAX(TOTAL_REVENUE) AS MAXREV FROM REVENUE0) AS TEMP
WHERE S_SUPPKEY = SUPPLIER_NO AND
      TOTAL_REVENUE = TEMP.MAXREV
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE0;

