-- TPC-D Parameter Substitution (Version 1.1.0D)
-- using default substitutions

set schema 'tpch';

SELECT O_ORDERPRIORITY, COUNT(*) AS ORDER_COUNT
FROM ORDERS,
     (SELECT L_ORDERKEY
      FROM LINEITEM
      WHERE L_COMMITDATE < L_RECEIPTDATE
      GROUP BY L_ORDERKEY) AS TEMP
WHERE
    O_ORDERDATE >= DATE'1993-07-01' AND
    O_ORDERDATE < DATE'1993-10-01' AND
    O_ORDERKEY = TEMP.L_ORDERKEY
GROUP BY O_ORDERPRIORITY
ORDER BY O_ORDERPRIORITY;


