-- TPC-D Parameter Substitution (Version 1.1.0D)
-- using default substitutions

set schema 'tpch'; 

SELECT NATION, YYEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM (SELECT N_NAME AS NATION,  
      SUBSTRING(CAST(O_ORDERDATE AS VARCHAR(10)) FROM 1 FOR 4) AS YYEAR,
      L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
        FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
        WHERE S_SUPPKEY = L_SUPPKEY
               AND PS_SUPPKEY = L_SUPPKEY
               AND PS_PARTKEY = L_PARTKEY
               AND P_PARTKEY = L_PARTKEY
               AND O_ORDERKEY = L_ORDERKEY
               AND S_NATIONKEY = N_NATIONKEY
               AND P_NAME LIKE '%green%'
      ) AS PROFIT
GROUP BY NATION, YYEAR
ORDER BY NATION, YYEAR;
--ORDER BY NATION, YEAR DESC;
