-- Q9 (tpch2.6.1)

SELECT
    NATION,
    YYEAR,
    SUM(AMOUNT) AS SUM_PROFIT
FROM (SELECT
          N_NAME AS NATION,  
          APPLIB.DATE_TO_CHAR('yyyy', O_ORDERDATE) AS YYEAR,
          L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
      FROM
          TPCH.PART,
          TPCH.SUPPLIER,
          TPCH.LINEITEM,
          TPCH.PARTSUPP,
          TPCH.ORDERS,
          TPCH.NATION
      WHERE
          S_SUPPKEY = L_SUPPKEY
          AND PS_SUPPKEY = L_SUPPKEY
          AND PS_PARTKEY = L_PARTKEY
          AND P_PARTKEY = L_PARTKEY
          AND O_ORDERKEY = L_ORDERKEY
          AND S_NATIONKEY = N_NATIONKEY
          AND P_NAME LIKE '%green%'
      ) AS PROFIT
GROUP BY
    NATION,
    YYEAR
ORDER BY
    NATION,
    YYEAR DESC;
