set schema 'tpch';

---------------------------
-- indices for foreign keys
---------------------------

-- table NATION: N_REGIONKEY
CREATE INDEX N_REGIONKEY_IDX ON NATION(N_REGIONKEY);

-- table REGION: none

-- table PART: none

-- table SUPPLIER: S_NATIONKEY
CREATE INDEX S_NATIONKEY_IDX ON SUPPLIER(S_NATIONKEY);

-- table PARTSUPP: PS_PARTKEY, PS_SUPPKEY
CREATE INDEX PS_PARTKEY_IDX ON PARTSUPP(PS_PARTKEY);
CREATE INDEX PS_SUPPKEY_IDX ON PARTSUPP(PS_SUPPKEY);

-- table CUSTOMER:C_NATIONKEY
CREATE INDEX C_NATIONKEY_IDX ON CUSTOMER(C_NATIONKEY);

-- table ORDERS: O_CUSTKEY
CREATE INDEX O_CUSTKEY_IDX ON ORDERS(O_CUSTKEY);

-- table LINEITEM: L_ORDERKEY, <L_PARTKEY,L_SUPPKEY>
CREATE INDEX L_ORDERKEY_IDX ON LINEITEM(L_ORDERKEY);
CREATE INDEX L_PARTSUPPKEY_IDX ON LINEITEM(L_PARTKEY,L_SUPPKEY);

----------------------------
-- indices for WHERE clauses
----------------------------

-- 1
CREATE INDEX L_SHIPDATE_IDX ON LINEITEM(L_SHIPDATE);

-- 3
CREATE INDEX C_MKTSEGMENT_IDX ON CUSTOMER(C_MKTSEGMENT);
CREATE INDEX O_ORDERDATE_IDX ON ORDERS(O_ORDERDATE);

-- 5
CREATE INDEX L_SUPPKEY_IDX ON LINEITEM(L_SUPPKEY);
CREATE INDEX R_NAME_IDX ON REGION(R_NAME);

-- 6
CREATE INDEX L_DISCOUNT_IDX ON LINEITEM(L_DISCOUNT);
CREATE INDEX L_QUANTITY_IDX ON LINEITEM(L_QUANTITY);

-- 10
CREATE INDEX L_RETURNFLAG_IDX ON LINEITEM(L_RETURNFLAG);

-- 12
CREATE INDEX L_SHIPMODE_IDX ON LINEITEM(L_SHIPMODE);
CREATE INDEX L_COMMITDATE_IDX ON LINEITEM(L_COMMITDATE);
CREATE INDEX L_RECEIPTDATE_IDX ON LINEITEM(L_RECEIPTDATE);

-- 14
CREATE INDEX L_PARTKEY_IDX ON LINEITEM(L_PARTKEY);

-- 2
CREATE INDEX P_SIZE_IDX ON PART(P_SIZE);
CREATE INDEX P_TYPE_IDX ON PART(P_TYPE);
CREATE INDEX PS_SUPPLYCOST_IDX ON PARTSUPP(PS_SUPPLYCOST);

-- 4: none

-- 7
CREATE INDEX N_NAME_IDX ON NATION(N_NAME);

-- 8: none

-- 9
CREATE INDEX P_NAME_IDX ON PART(P_NAME);

-- 11: none

-- 13
CREATE INDEX O_CLERK_IDX ON ORDERS(O_CLERK);

-- 15: none

-- 16
CREATE INDEX P_BRAND_IDX ON PART(P_BRAND);

-- 17
CREATE INDEX P_CONTAINER_IDX ON PART(P_CONTAINER);

-----------------
-- analyze tables
-----------------
ANALYZE TABLE NATION ESTIMATE STATISTICS FOR ALL COLUMNS;
ANALYZE TABLE REGION ESTIMATE STATISTICS FOR ALL COLUMNS;
ANALYZE TABLE PART ESTIMATE STATISTICS FOR ALL COLUMNS;
ANALYZE TABLE SUPPLIER ESTIMATE STATISTICS FOR ALL COLUMNS;
ANALYZE TABLE PARTSUPP ESTIMATE STATISTICS FOR ALL COLUMNS;
ANALYZE TABLE CUSTOMER ESTIMATE STATISTICS FOR ALL COLUMNS;
ANALYZE TABLE ORDERS ESTIMATE STATISTICS FOR ALL COLUMNS;
ANALYZE TABLE LINEITEM ESTIMATE STATISTICS FOR ALL COLUMNS;
