--
-- bug6604.sql: internal error for 'case <column> = <value>'
--

set schema 's';

CREATE TABLE ITEMS (
 ITEM_ID SMALLINT,
 CD_TITLE VARCHAR(255),
 LABEL VARCHAR(255),
 RELEASE_DATE DATE,
 ARTIST_GROUP VARCHAR(255),
 COMPOSER VARCHAR(255),
 PRICE NUMERIC(19,4),
 CATEGORY VARCHAR(255) )
;
CREATE TABLE SALES (
 Store_ID SMALLINT,
 Item_ID SMALLINT,
 Order_Date DATE,
 Units SMALLINT,
 Amount NUMERIC(19,4) )
;
SELECT ITEMS.COMPOSER, ITEMS.PRICE, SALES.AMOUNT,
 case when ITEMS.COMPOSER = 'Babyface' then ITEMS.PRICE
 else SALES.AMOUNT end as TESTCASE
FROM ITEMS join SALES on ITEMS.ITEM_ID = SALES.ITEM_ID
;
SELECT ITEMS.COMPOSER, ITEMS.PRICE, SALES.AMOUNT,
 case when ITEMS.COMPOSER <> 'Babyface' then SALES.AMOUNT
 else ITEMS.PRICE end as TESTCASE
FROM ITEMS join SALES on ITEMS.ITEM_ID = SALES.ITEM_ID
;
SELECT ITEMS.COMPOSER, ITEMS.PRICE, SALES.AMOUNT,
 case when ITEMS.COMPOSER = 'Babyface' then ITEMS.PRICE
 else 0 end as TESTCASE
FROM ITEMS join SALES on ITEMS.ITEM_ID = SALES.ITEM_ID
;

-- End bug6604.sql
